# State dict keys and shapes for an XLabs FLUX IP-Adapter model. Intended to be used for unit tests.
# These keys were extracted from:
# https://huggingface.co/XLabs-AI/flux-ip-adapter/resolve/main/ip_adapter.safetensors
xlabs_flux_ip_adapter_sd_shapes = {
    "double_blocks.0.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.0.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.0.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.0.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.1.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.1.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.1.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.1.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.10.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.10.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.10.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.10.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.11.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.11.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.11.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.11.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.12.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.12.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.12.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.12.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.13.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.13.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.13.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.13.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.14.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.14.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.14.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.14.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.15.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.15.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.15.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.15.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.16.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.16.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.16.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.16.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.17.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.17.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.17.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.17.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.18.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.18.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.18.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.18.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.2.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.2.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.2.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.2.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.3.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.3.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.3.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.3.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.4.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.4.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.4.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.4.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.5.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.5.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.5.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.5.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.6.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.6.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.6.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.6.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.7.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.7.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.7.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.7.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.8.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.8.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.8.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.8.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "double_blocks.9.processor.ip_adapter_double_stream_k_proj.bias": [3072],
    "double_blocks.9.processor.ip_adapter_double_stream_k_proj.weight": [3072, 4096],
    "double_blocks.9.processor.ip_adapter_double_stream_v_proj.bias": [3072],
    "double_blocks.9.processor.ip_adapter_double_stream_v_proj.weight": [3072, 4096],
    "ip_adapter_proj_model.norm.bias": [4096],
    "ip_adapter_proj_model.norm.weight": [4096],
    "ip_adapter_proj_model.proj.bias": [16384],
    "ip_adapter_proj_model.proj.weight": [16384, 768],
}
