"""The semantic connector Anima-3.8B v1.1 bundles, as its checkpoint records it.

Captured from `lylogummy/Anima-3.8B` `difussion_models/Anima-3.8B-v1.1.safetensors` (bf16, 1358 tensors):
all 190 tensors under `net.anima_v2_connector.`, and the header entries the loader and identification
read. The DiT itself is 52 blocks with the per-block layout of the official release (see
`anima_2_9b_keys.py`); `qwen35_joint_dit_blocks` is the header key that marks a checkpoint trained jointly
with Qwen3.5 -- present here and in the unbundled v1.0 DiT.
"""

ANIMA_3_8B_NUM_BLOCKS = 52

metadata: dict[str, str] = {
    "anima_v2_adapter_architecture": "anima_qwen35_quality_anchored_semantic_connector_v2",
    "anima_v2_adapter_layer_indices": "[7, 15, 23, 31]",
    "anima_v2_adapter_semantic_query_tokens": "64",
    "anima_v2_adapter_semantic_resampler_blocks": "6",
    "anima_v2_adapter_semantic_resampler_dim": "2048",
    "anima_v2_adapter_semantic_resampler_heads": "16",
    "anima_v2_adapter_semantic_resampler_mlp_hidden_dim": "5632",
    "architecture": "anima_3_8b_semantic_connector_v2_bundle",
    "anima_v2_bundle_format": "1",
    "anima_v2_connector_prefix": "net.anima_v2_connector.",
    "new_block_count": "52",
    "qwen35_joint_dit_blocks": "[0, 1, 2, 4, 5, 6, 7, 8, 10, 11, 12, 14, 16, 17, 18, 19, 21, 22, 24, 25, 27, 28, 30, 31, 32, 33, 34, 36, 38, 40, 43, 44, 46, 49, 50]",
}

connector_keys: dict[str, list[int]] = {
    "net.anima_v2_connector.quality_anchor.layer_mix_logits": [6, 4],
    "net.anima_v2_connector.quality_anchor.query_norms.0.weight": [1024],
    "net.anima_v2_connector.quality_anchor.query_norms.1.weight": [1024],
    "net.anima_v2_connector.quality_anchor.query_norms.2.weight": [1024],
    "net.anima_v2_connector.quality_anchor.query_norms.3.weight": [1024],
    "net.anima_v2_connector.quality_anchor.query_norms.4.weight": [1024],
    "net.anima_v2_connector.quality_anchor.query_norms.5.weight": [1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.0.k_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.0.k_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.0.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.0.q_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.0.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.0.v_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.1.k_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.1.k_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.1.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.1.q_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.1.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.1.v_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.2.k_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.2.k_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.2.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.2.q_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.2.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.2.v_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.3.k_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.3.k_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.3.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.3.q_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.3.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.3.v_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.4.k_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.4.k_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.4.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.4.q_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.4.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.4.v_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.5.k_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.5.k_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.5.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.5.q_norm.weight": [64],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.5.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.quality_anchor.semantic_attentions.5.v_proj.weight": [1024, 2560],
    "net.anima_v2_connector.quality_anchor.source_norms.0.weight": [2560],
    "net.anima_v2_connector.quality_anchor.source_norms.1.weight": [2560],
    "net.anima_v2_connector.quality_anchor.source_norms.2.weight": [2560],
    "net.anima_v2_connector.quality_anchor.source_norms.3.weight": [2560],
    "net.anima_v2_connector.quality_anchor.source_norms.4.weight": [2560],
    "net.anima_v2_connector.quality_anchor.source_norms.5.weight": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.0.cross_attention.k_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.0.cross_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.0.cross_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.0.cross_attention.v_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.0.mlp_in.weight": [11264, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.0.mlp_out.weight": [2048, 5632],
    "net.anima_v2_connector.semantic_resampler.blocks.0.self_attention.k_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.0.self_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.0.self_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.0.self_attention.v_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.0.source_norm.bias": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.0.source_norm.weight": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.0.time_modulation.bias": [12288],
    "net.anima_v2_connector.semantic_resampler.blocks.0.time_modulation.weight": [12288, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.cross_attention.k_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.1.cross_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.cross_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.cross_attention.v_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.1.mlp_in.weight": [11264, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.mlp_out.weight": [2048, 5632],
    "net.anima_v2_connector.semantic_resampler.blocks.1.self_attention.k_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.self_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.self_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.self_attention.v_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.1.source_norm.bias": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.1.source_norm.weight": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.1.time_modulation.bias": [12288],
    "net.anima_v2_connector.semantic_resampler.blocks.1.time_modulation.weight": [12288, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.cross_attention.k_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.2.cross_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.cross_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.cross_attention.v_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.2.mlp_in.weight": [11264, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.mlp_out.weight": [2048, 5632],
    "net.anima_v2_connector.semantic_resampler.blocks.2.self_attention.k_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.self_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.self_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.self_attention.v_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.2.source_norm.bias": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.2.source_norm.weight": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.2.time_modulation.bias": [12288],
    "net.anima_v2_connector.semantic_resampler.blocks.2.time_modulation.weight": [12288, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.cross_attention.k_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.3.cross_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.cross_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.cross_attention.v_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.3.mlp_in.weight": [11264, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.mlp_out.weight": [2048, 5632],
    "net.anima_v2_connector.semantic_resampler.blocks.3.self_attention.k_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.self_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.self_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.self_attention.v_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.3.source_norm.bias": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.3.source_norm.weight": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.3.time_modulation.bias": [12288],
    "net.anima_v2_connector.semantic_resampler.blocks.3.time_modulation.weight": [12288, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.cross_attention.k_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.4.cross_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.cross_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.cross_attention.v_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.4.mlp_in.weight": [11264, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.mlp_out.weight": [2048, 5632],
    "net.anima_v2_connector.semantic_resampler.blocks.4.self_attention.k_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.self_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.self_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.self_attention.v_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.4.source_norm.bias": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.4.source_norm.weight": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.4.time_modulation.bias": [12288],
    "net.anima_v2_connector.semantic_resampler.blocks.4.time_modulation.weight": [12288, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.cross_attention.k_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.5.cross_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.cross_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.cross_attention.v_proj.weight": [2048, 2560],
    "net.anima_v2_connector.semantic_resampler.blocks.5.mlp_in.weight": [11264, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.mlp_out.weight": [2048, 5632],
    "net.anima_v2_connector.semantic_resampler.blocks.5.self_attention.k_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.self_attention.o_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.self_attention.q_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.self_attention.v_proj.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.blocks.5.source_norm.bias": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.5.source_norm.weight": [2560],
    "net.anima_v2_connector.semantic_resampler.blocks.5.time_modulation.bias": [12288],
    "net.anima_v2_connector.semantic_resampler.blocks.5.time_modulation.weight": [12288, 2048],
    "net.anima_v2_connector.semantic_resampler.layer_embeddings": [4, 1, 2560],
    "net.anima_v2_connector.semantic_resampler.output_norm.bias": [2048],
    "net.anima_v2_connector.semantic_resampler.output_norm.weight": [2048],
    "net.anima_v2_connector.semantic_resampler.output_projection.weight": [1024, 2048],
    "net.anima_v2_connector.semantic_resampler.query_tokens": [1, 64, 2048],
    "net.anima_v2_connector.semantic_resampler.time_mlp.0.bias": [2048],
    "net.anima_v2_connector.semantic_resampler.time_mlp.0.weight": [2048, 2048],
    "net.anima_v2_connector.semantic_resampler.time_mlp.2.bias": [2048],
    "net.anima_v2_connector.semantic_resampler.time_mlp.2.weight": [2048, 2048],
    "net.anima_v2_connector.v2_attentions.0.k_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.0.k_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.0.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.0.q_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.0.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.0.v_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.1.k_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.1.k_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.1.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.1.q_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.1.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.1.v_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.2.k_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.2.k_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.2.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.2.q_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.2.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.2.v_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.3.k_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.3.k_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.3.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.3.q_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.3.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.3.v_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.4.k_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.4.k_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.4.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.4.q_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.4.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.4.v_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.5.k_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.5.k_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.5.o_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.5.q_norm.weight": [64],
    "net.anima_v2_connector.v2_attentions.5.q_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_attentions.5.v_proj.weight": [1024, 1024],
    "net.anima_v2_connector.v2_query_norms.0.weight": [1024],
    "net.anima_v2_connector.v2_query_norms.1.weight": [1024],
    "net.anima_v2_connector.v2_query_norms.2.weight": [1024],
    "net.anima_v2_connector.v2_query_norms.3.weight": [1024],
    "net.anima_v2_connector.v2_query_norms.4.weight": [1024],
    "net.anima_v2_connector.v2_query_norms.5.weight": [1024],
    "net.anima_v2_connector.v2_semantic_norms.0.weight": [1024],
    "net.anima_v2_connector.v2_semantic_norms.1.weight": [1024],
    "net.anima_v2_connector.v2_semantic_norms.2.weight": [1024],
    "net.anima_v2_connector.v2_semantic_norms.3.weight": [1024],
    "net.anima_v2_connector.v2_semantic_norms.4.weight": [1024],
    "net.anima_v2_connector.v2_semantic_norms.5.weight": [1024],
}
