"""Representative key layout of a *scaled* fp8 FLUX.1 dev transformer checkpoint.

Captured from `comfyanonymous/flux_dev_scaled_fp8_test`, the reference ComfyUI scaled-fp8 export
for FLUX.1. Every key in that file carries the `model.diffusion_model.` bundle prefix; this fixture
records them as they look *after* `convert_bundle_to_flux_transformer_checkpoint` has stripped it,
which is where the loader reads them.

Worth capturing for three reasons. It spells the scales `.scale_weight`/`.scale_input` rather than
`.weight_scale`/`.input_scale`, so it exercises the second spelling end to end. Every one of its
314 quantized Linears carries a *calibrated* `scale_input` -- not the uncalibrated 1.0 placeholder
that `_usable_input_scale` rejects -- which no other captured fixture provides. And its `qkv` stays
one fused `[9216, 3072]` Linear with a single scalar scale, matching the BFL layout InvokeAI's own
`Flux` implements, so no scale has to be split or copied.

Before scaled-fp8 support reached this loader the file did not load at all: 629 scale and marker
keys reached `load_state_dict` as unexpected keys.

Subsetting rule as for the sibling fixtures: block 0 of each stack plus every non-block key.
Values are `(shape, dtype)`.
"""

state_dict_keys: dict[str, tuple[list[int], str]] = {
    "double_blocks.0.img_attn.norm.key_norm.scale": ([128], "BF16"),
    "double_blocks.0.img_attn.norm.query_norm.scale": ([128], "BF16"),
    "double_blocks.0.img_attn.proj.bias": ([3072], "F8_E4M3"),
    "double_blocks.0.img_attn.proj.scale_input": ([], "F32"),
    "double_blocks.0.img_attn.proj.scale_weight": ([], "F32"),
    "double_blocks.0.img_attn.proj.weight": ([3072, 3072], "F8_E4M3"),
    "double_blocks.0.img_attn.qkv.bias": ([9216], "F8_E4M3"),
    "double_blocks.0.img_attn.qkv.scale_input": ([], "F32"),
    "double_blocks.0.img_attn.qkv.scale_weight": ([], "F32"),
    "double_blocks.0.img_attn.qkv.weight": ([9216, 3072], "F8_E4M3"),
    "double_blocks.0.img_mlp.0.bias": ([12288], "F8_E4M3"),
    "double_blocks.0.img_mlp.0.scale_input": ([], "F32"),
    "double_blocks.0.img_mlp.0.scale_weight": ([], "F32"),
    "double_blocks.0.img_mlp.0.weight": ([12288, 3072], "F8_E4M3"),
    "double_blocks.0.img_mlp.2.bias": ([3072], "F8_E4M3"),
    "double_blocks.0.img_mlp.2.scale_input": ([], "F32"),
    "double_blocks.0.img_mlp.2.scale_weight": ([], "F32"),
    "double_blocks.0.img_mlp.2.weight": ([3072, 12288], "F8_E4M3"),
    "double_blocks.0.img_mod.lin.bias": ([18432], "F8_E4M3"),
    "double_blocks.0.img_mod.lin.scale_input": ([], "F32"),
    "double_blocks.0.img_mod.lin.scale_weight": ([], "F32"),
    "double_blocks.0.img_mod.lin.weight": ([18432, 3072], "F8_E4M3"),
    "double_blocks.0.txt_attn.norm.key_norm.scale": ([128], "BF16"),
    "double_blocks.0.txt_attn.norm.query_norm.scale": ([128], "BF16"),
    "double_blocks.0.txt_attn.proj.bias": ([3072], "F8_E4M3"),
    "double_blocks.0.txt_attn.proj.scale_input": ([], "F32"),
    "double_blocks.0.txt_attn.proj.scale_weight": ([], "F32"),
    "double_blocks.0.txt_attn.proj.weight": ([3072, 3072], "F8_E4M3"),
    "double_blocks.0.txt_attn.qkv.bias": ([9216], "F8_E4M3"),
    "double_blocks.0.txt_attn.qkv.scale_input": ([], "F32"),
    "double_blocks.0.txt_attn.qkv.scale_weight": ([], "F32"),
    "double_blocks.0.txt_attn.qkv.weight": ([9216, 3072], "F8_E4M3"),
    "double_blocks.0.txt_mlp.0.bias": ([12288], "F8_E4M3"),
    "double_blocks.0.txt_mlp.0.scale_input": ([], "F32"),
    "double_blocks.0.txt_mlp.0.scale_weight": ([], "F32"),
    "double_blocks.0.txt_mlp.0.weight": ([12288, 3072], "F8_E4M3"),
    "double_blocks.0.txt_mlp.2.bias": ([3072], "F8_E4M3"),
    "double_blocks.0.txt_mlp.2.scale_input": ([], "F32"),
    "double_blocks.0.txt_mlp.2.scale_weight": ([], "F32"),
    "double_blocks.0.txt_mlp.2.weight": ([3072, 12288], "F8_E4M3"),
    "double_blocks.0.txt_mod.lin.bias": ([18432], "F8_E4M3"),
    "double_blocks.0.txt_mod.lin.scale_input": ([], "F32"),
    "double_blocks.0.txt_mod.lin.scale_weight": ([], "F32"),
    "double_blocks.0.txt_mod.lin.weight": ([18432, 3072], "F8_E4M3"),
    "final_layer.adaLN_modulation.1.bias": ([6144], "F8_E4M3"),
    "final_layer.adaLN_modulation.1.scale_input": ([], "F32"),
    "final_layer.adaLN_modulation.1.scale_weight": ([], "F32"),
    "final_layer.adaLN_modulation.1.weight": ([6144, 3072], "F8_E4M3"),
    "final_layer.linear.bias": ([64], "F8_E4M3"),
    "final_layer.linear.scale_input": ([], "F32"),
    "final_layer.linear.scale_weight": ([], "F32"),
    "final_layer.linear.weight": ([64, 3072], "F8_E4M3"),
    "guidance_in.in_layer.bias": ([3072], "F8_E4M3"),
    "guidance_in.in_layer.scale_input": ([], "F32"),
    "guidance_in.in_layer.scale_weight": ([], "F32"),
    "guidance_in.in_layer.weight": ([3072, 256], "F8_E4M3"),
    "guidance_in.out_layer.bias": ([3072], "F8_E4M3"),
    "guidance_in.out_layer.scale_input": ([], "F32"),
    "guidance_in.out_layer.scale_weight": ([], "F32"),
    "guidance_in.out_layer.weight": ([3072, 3072], "F8_E4M3"),
    "img_in.bias": ([3072], "F8_E4M3"),
    "img_in.scale_input": ([], "F32"),
    "img_in.scale_weight": ([], "F32"),
    "img_in.weight": ([3072, 64], "F8_E4M3"),
    "scaled_fp8": ([0], "F8_E4M3"),
    "single_blocks.0.linear1.bias": ([21504], "F8_E4M3"),
    "single_blocks.0.linear1.scale_input": ([], "F32"),
    "single_blocks.0.linear1.scale_weight": ([], "F32"),
    "single_blocks.0.linear1.weight": ([21504, 3072], "F8_E4M3"),
    "single_blocks.0.linear2.bias": ([3072], "F8_E4M3"),
    "single_blocks.0.linear2.scale_input": ([], "F32"),
    "single_blocks.0.linear2.scale_weight": ([], "F32"),
    "single_blocks.0.linear2.weight": ([3072, 15360], "F8_E4M3"),
    "single_blocks.0.modulation.lin.bias": ([9216], "F8_E4M3"),
    "single_blocks.0.modulation.lin.scale_input": ([], "F32"),
    "single_blocks.0.modulation.lin.scale_weight": ([], "F32"),
    "single_blocks.0.modulation.lin.weight": ([9216, 3072], "F8_E4M3"),
    "single_blocks.0.norm.key_norm.scale": ([128], "BF16"),
    "single_blocks.0.norm.query_norm.scale": ([128], "BF16"),
    "time_in.in_layer.bias": ([3072], "F8_E4M3"),
    "time_in.in_layer.scale_input": ([], "F32"),
    "time_in.in_layer.scale_weight": ([], "F32"),
    "time_in.in_layer.weight": ([3072, 256], "F8_E4M3"),
    "time_in.out_layer.bias": ([3072], "F8_E4M3"),
    "time_in.out_layer.scale_input": ([], "F32"),
    "time_in.out_layer.scale_weight": ([], "F32"),
    "time_in.out_layer.weight": ([3072, 3072], "F8_E4M3"),
    "txt_in.bias": ([3072], "F8_E4M3"),
    "txt_in.scale_input": ([], "F32"),
    "txt_in.scale_weight": ([], "F32"),
    "txt_in.weight": ([3072, 4096], "F8_E4M3"),
    "vector_in.in_layer.bias": ([3072], "F8_E4M3"),
    "vector_in.in_layer.scale_input": ([], "F32"),
    "vector_in.in_layer.scale_weight": ([], "F32"),
    "vector_in.in_layer.weight": ([3072, 768], "F8_E4M3"),
    "vector_in.out_layer.bias": ([3072], "F8_E4M3"),
    "vector_in.out_layer.scale_input": ([], "F32"),
    "vector_in.out_layer.scale_weight": ([], "F32"),
    "vector_in.out_layer.weight": ([3072, 3072], "F8_E4M3"),
}
