"""Representative key layout of Comfy-Org's MXFP8 Krea-2 Turbo build.

Captured on 2026-09-26 with `scripts/capture_state_dict_fixture.py`,
which reads the header only, from
`Comfy-Org/Krea-2/diffusion_models/krea2_turbo_mxfp8.safetensors`.

Subsetting rule: `blocks` index 0, plus every key outside a stack. Values are `(shape, dtype)`.

The only reachable MXFP8 file, and the only checked-in evidence for what the scheme looks like on
disk. Everything the decode assumes is visible here: the scale is `uint8` rather than a float, one
entry per 32 weight elements, a whole number of cuBLAS tiles, and the layer is named `mxfp8` in the
`_quantization_metadata` header with **no** per-tensor `.comfy_quant` marker beside it.

`block_size` is absent from every hint. `decode_mx_block_scales` takes the block width from the
shapes for exactly that reason and lets the marker only cross-check it; a decode that required the
field would refuse this file, and a re-upload that added it must not change the answer.

No weights can be checked in -- this build is `license: other` -- so what is recorded is the layout,
and the block width the synthetic payloads are built from is checked against the width stored here.
"""

state_dict_keys: dict[str, tuple[list[int], str]] = {
    "blocks.0.attn.gate.weight": ([6144, 6144], "F8_E4M3"),
    "blocks.0.attn.gate.weight_scale": ([6144, 192], "U8"),
    "blocks.0.attn.qknorm.knorm.scale": ([128], "BF16"),
    "blocks.0.attn.qknorm.qnorm.scale": ([128], "BF16"),
    "blocks.0.attn.wk.weight": ([1536, 6144], "F8_E4M3"),
    "blocks.0.attn.wk.weight_scale": ([1536, 192], "U8"),
    "blocks.0.attn.wo.weight": ([6144, 6144], "F8_E4M3"),
    "blocks.0.attn.wo.weight_scale": ([6144, 192], "U8"),
    "blocks.0.attn.wq.weight": ([6144, 6144], "F8_E4M3"),
    "blocks.0.attn.wq.weight_scale": ([6144, 192], "U8"),
    "blocks.0.attn.wv.weight": ([1536, 6144], "F8_E4M3"),
    "blocks.0.attn.wv.weight_scale": ([1536, 192], "U8"),
    "blocks.0.mlp.down.weight": ([6144, 16384], "F8_E4M3"),
    "blocks.0.mlp.down.weight_scale": ([6144, 512], "U8"),
    "blocks.0.mlp.gate.weight": ([16384, 6144], "F8_E4M3"),
    "blocks.0.mlp.gate.weight_scale": ([16384, 192], "U8"),
    "blocks.0.mlp.up.weight": ([16384, 6144], "F8_E4M3"),
    "blocks.0.mlp.up.weight_scale": ([16384, 192], "U8"),
    "blocks.0.mod.lin": ([36864], "BF16"),
    "blocks.0.postnorm.scale": ([6144], "BF16"),
    "blocks.0.prenorm.scale": ([6144], "BF16"),
    "first.bias": ([6144], "BF16"),
    "first.weight": ([6144, 64], "BF16"),
    "last.linear.bias": ([64], "BF16"),
    "last.linear.weight": ([64, 6144], "BF16"),
    "last.modulation.lin": ([2, 6144], "BF16"),
    "last.norm.scale": ([6144], "BF16"),
    "tmlp.0.bias": ([6144], "BF16"),
    "tmlp.0.weight": ([6144, 256], "BF16"),
    "tmlp.2.bias": ([6144], "BF16"),
    "tmlp.2.weight": ([6144, 6144], "BF16"),
    "tproj.1.bias": ([36864], "BF16"),
    "tproj.1.weight": ([36864, 6144], "BF16"),
    "txtfusion.layerwise_blocks.0.attn.gate.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.attn.gate.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.0.attn.qknorm.knorm.scale": ([128], "BF16"),
    "txtfusion.layerwise_blocks.0.attn.qknorm.qnorm.scale": ([128], "BF16"),
    "txtfusion.layerwise_blocks.0.attn.wk.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.attn.wk.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.0.attn.wo.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.attn.wo.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.0.attn.wq.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.attn.wq.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.0.attn.wv.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.attn.wv.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.0.mlp.down.weight": ([2560, 6912], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.mlp.down.weight_scale": ([2560, 216], "U8"),
    "txtfusion.layerwise_blocks.0.mlp.gate.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.mlp.gate.weight_scale": ([6912, 80], "U8"),
    "txtfusion.layerwise_blocks.0.mlp.up.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.0.mlp.up.weight_scale": ([6912, 80], "U8"),
    "txtfusion.layerwise_blocks.0.postnorm.scale": ([2560], "BF16"),
    "txtfusion.layerwise_blocks.0.prenorm.scale": ([2560], "BF16"),
    "txtfusion.layerwise_blocks.1.attn.gate.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.attn.gate.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.1.attn.qknorm.knorm.scale": ([128], "BF16"),
    "txtfusion.layerwise_blocks.1.attn.qknorm.qnorm.scale": ([128], "BF16"),
    "txtfusion.layerwise_blocks.1.attn.wk.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.attn.wk.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.1.attn.wo.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.attn.wo.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.1.attn.wq.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.attn.wq.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.1.attn.wv.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.attn.wv.weight_scale": ([2560, 80], "U8"),
    "txtfusion.layerwise_blocks.1.mlp.down.weight": ([2560, 6912], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.mlp.down.weight_scale": ([2560, 216], "U8"),
    "txtfusion.layerwise_blocks.1.mlp.gate.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.mlp.gate.weight_scale": ([6912, 80], "U8"),
    "txtfusion.layerwise_blocks.1.mlp.up.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.layerwise_blocks.1.mlp.up.weight_scale": ([6912, 80], "U8"),
    "txtfusion.layerwise_blocks.1.postnorm.scale": ([2560], "BF16"),
    "txtfusion.layerwise_blocks.1.prenorm.scale": ([2560], "BF16"),
    "txtfusion.projector.weight": ([1, 12], "BF16"),
    "txtfusion.refiner_blocks.0.attn.gate.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.attn.gate.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.0.attn.qknorm.knorm.scale": ([128], "BF16"),
    "txtfusion.refiner_blocks.0.attn.qknorm.qnorm.scale": ([128], "BF16"),
    "txtfusion.refiner_blocks.0.attn.wk.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.attn.wk.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.0.attn.wo.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.attn.wo.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.0.attn.wq.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.attn.wq.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.0.attn.wv.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.attn.wv.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.0.mlp.down.weight": ([2560, 6912], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.mlp.down.weight_scale": ([2560, 216], "U8"),
    "txtfusion.refiner_blocks.0.mlp.gate.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.mlp.gate.weight_scale": ([6912, 80], "U8"),
    "txtfusion.refiner_blocks.0.mlp.up.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.0.mlp.up.weight_scale": ([6912, 80], "U8"),
    "txtfusion.refiner_blocks.0.postnorm.scale": ([2560], "BF16"),
    "txtfusion.refiner_blocks.0.prenorm.scale": ([2560], "BF16"),
    "txtfusion.refiner_blocks.1.attn.gate.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.attn.gate.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.1.attn.qknorm.knorm.scale": ([128], "BF16"),
    "txtfusion.refiner_blocks.1.attn.qknorm.qnorm.scale": ([128], "BF16"),
    "txtfusion.refiner_blocks.1.attn.wk.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.attn.wk.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.1.attn.wo.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.attn.wo.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.1.attn.wq.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.attn.wq.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.1.attn.wv.weight": ([2560, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.attn.wv.weight_scale": ([2560, 80], "U8"),
    "txtfusion.refiner_blocks.1.mlp.down.weight": ([2560, 6912], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.mlp.down.weight_scale": ([2560, 216], "U8"),
    "txtfusion.refiner_blocks.1.mlp.gate.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.mlp.gate.weight_scale": ([6912, 80], "U8"),
    "txtfusion.refiner_blocks.1.mlp.up.weight": ([6912, 2560], "F8_E4M3"),
    "txtfusion.refiner_blocks.1.mlp.up.weight_scale": ([6912, 80], "U8"),
    "txtfusion.refiner_blocks.1.postnorm.scale": ([2560], "BF16"),
    "txtfusion.refiner_blocks.1.prenorm.scale": ([2560], "BF16"),
    "txtmlp.0.scale": ([2560], "BF16"),
    "txtmlp.1.bias": ([6144], "BF16"),
    "txtmlp.1.weight": ([6144, 2560], "BF16"),
    "txtmlp.3.bias": ([6144], "BF16"),
    "txtmlp.3.weight": ([6144, 6144], "BF16"),
}

# The `_quantization_metadata` header block, layer names exactly as the producer wrote them.
layer_hints: dict[str, dict[str, object]] = {
    "blocks.0.attn.gate": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "blocks.0.attn.wk": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "blocks.0.attn.wo": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "blocks.0.attn.wq": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "blocks.0.attn.wv": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "blocks.0.mlp.down": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "blocks.0.mlp.gate": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "blocks.0.mlp.up": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.0.attn.gate": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.layerwise_blocks.0.attn.wk": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.0.attn.wo": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.layerwise_blocks.0.attn.wq": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.0.attn.wv": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.0.mlp.down": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.layerwise_blocks.0.mlp.gate": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.0.mlp.up": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.1.attn.gate": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.layerwise_blocks.1.attn.wk": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.1.attn.wo": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.layerwise_blocks.1.attn.wq": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.1.attn.wv": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.1.mlp.down": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.layerwise_blocks.1.mlp.gate": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.layerwise_blocks.1.mlp.up": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.0.attn.gate": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.refiner_blocks.0.attn.wk": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.0.attn.wo": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.refiner_blocks.0.attn.wq": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.0.attn.wv": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.0.mlp.down": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.refiner_blocks.0.mlp.gate": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.0.mlp.up": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.1.attn.gate": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.refiner_blocks.1.attn.wk": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.1.attn.wo": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.refiner_blocks.1.attn.wq": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.1.attn.wv": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.1.mlp.down": {"format": "mxfp8", "full_precision_matrix_mult": True},
    "txtfusion.refiner_blocks.1.mlp.gate": {"format": "mxfp8", "full_precision_matrix_mult": False},
    "txtfusion.refiner_blocks.1.mlp.up": {"format": "mxfp8", "full_precision_matrix_mult": False},
}
