# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: ruff-check
    name: ruff check
    stages: [pre-commit]
    language: system
    entry: uv tool run ruff@0.11.2 check --force-exclude
    types: [python]

  - id: ruff-format
    name: ruff format check
    stages: [pre-commit]
    language: system
    entry: uv tool run ruff@0.11.2 format --check --force-exclude
    types: [python]

  - id: uvlock
    name: uv lock
    stages: [pre-commit]
    language: system
    entry: uv lock
    files: ^pyproject\.toml$
    pass_filenames: false
