import { getCollection } from 'astro:content';
import { defineRouteMiddleware, type StarlightRouteData } from '@astrojs/starlight/route-data';

import { getSortPrefix, stripSortPrefix } from './lib/sort-prefix.mjs';

type SidebarEntry = StarlightRouteData['sidebar'][number];
type SidebarLink = Extract<SidebarEntry, { type: 'link' }>;
type PrevNextConfig = StarlightRouteData['entry']['data']['prev'];

const trimSlashes = (path: string) => path.replace(/^\/+|\/+$/g, '');
const basePath = trimSlashes(import.meta.env.BASE_URL);

/** Maps each docs page id to its file name, which keeps the sorting prefix the id drops. */
const getFileNamesById = async () => {
  const docs = await getCollection('docs');
  return new Map(docs.map((doc) => [doc.id, doc.filePath?.split('/').pop() ?? '']));
};

const hrefToId = (href: string) => {
  const path = trimSlashes(href);
  return basePath && path.startsWith(`${basePath}/`) ? path.slice(basePath.length + 1) : path;
};

/**
 * Starlight orders autogenerated entries by frontmatter `sidebar.order`, then by id, and ids no longer carry
 * the prefix. Reorder siblings generated from the same directory by prefix (unprefixed ones follow, in
 * Starlight's order) and strip the prefix from directory labels. Other entries keep their positions.
 */
const sortAndRelabel = (entries: SidebarEntry[], fileNames: Map<string, string>): boolean => {
  let changed = false;
  const sortKey = (entry: SidebarEntry) =>
    getSortPrefix(entry.type === 'group' ? entry.label : (fileNames.get(hrefToId(entry.href)) ?? '')) ??
    Number.POSITIVE_INFINITY;

  const slotsByDirectory = new Map<string, number[]>();
  entries.forEach((entry, index) => {
    const directory = 'autogenerate' in entry ? entry.autogenerate?.directory : undefined;
    if (directory !== undefined) slotsByDirectory.set(directory, [...(slotsByDirectory.get(directory) ?? []), index]);
  });
  for (const slots of slotsByDirectory.values()) {
    const sorted = slots.map((index) => entries[index]!).sort((a, b) => sortKey(a) - sortKey(b));
    slots.forEach((slot, i) => {
      if (entries[slot] !== sorted[i]) changed = true;
      entries[slot] = sorted[i]!;
    });
  }

  for (const entry of entries) {
    if (entry.type !== 'group') continue;
    if ('autogenerate' in entry && entry.autogenerate) entry.label = stripSortPrefix(entry.label);
    if (sortAndRelabel(entry.entries, fileNames)) changed = true;
  }
  return changed;
};

const flattenLinks = (entries: SidebarEntry[]): SidebarLink[] =>
  entries.flatMap((entry) => (entry.type === 'group' ? flattenLinks(entry.entries) : [entry]));

/** Mirrors Starlight's handling of the frontmatter `prev`/`next` options for a regenerated neighbour link. */
const applyPrevNextConfig = (link: SidebarLink | undefined, config: PrevNextConfig): SidebarLink | undefined => {
  if (config === false) return undefined;
  if (config === undefined || config === true) return link;
  if (typeof config === 'string') return link && { ...link, label: config };
  if (link) return { ...link, label: config.label ?? link.label, href: config.link ?? link.href, attrs: {} };
  if (config.link && config.label) {
    return { type: 'link', href: config.link, label: config.label, isCurrent: false, badge: undefined, attrs: {} };
  }
  return undefined;
};

export const onRequest = defineRouteMiddleware(async (context) => {
  const route = context.locals.starlightRoute;
  // Starlight hands each render its own copy of the sidebar.
  if (!sortAndRelabel(route.sidebar, await getFileNamesById())) return;

  // Starlight derived prev/next links before the reorder. This site keeps the default `pagination: true`.
  const links = flattenLinks(route.sidebar);
  const current = links.findIndex((link) => link.isCurrent);
  if (current === -1) return;
  const { data } = route.entry;
  route.pagination.prev = applyPrevNextConfig(links[current - 1], data.prev);
  route.pagination.next = applyPrevNextConfig(links[current + 1], data.next);
});
