import { getCollection } from 'astro:content';
import { defineRouteMiddleware, type StarlightRouteData } from '@astrojs/starlight/route-data';

import { generateDocsId, getSortPrefix, stripSortPrefix } from './lib/sort-prefix.mjs';

type SidebarEntry = StarlightRouteData['sidebar'][number];
type SidebarLink = Extract<SidebarEntry, { type: 'link' }>;
type PrevNextConfig = StarlightRouteData['entry']['data']['prev'];

const trimSlashes = (path: string) => path.replace(/^\/+|\/+$/g, '');
const basePath = trimSlashes(import.meta.env.BASE_URL);
const parentDirectory = (id: string) => id.slice(0, Math.max(id.lastIndexOf('/'), 0));

type CrossListing = { id: string; directory: string };

/** Marks the copy of a link that a page's `alsoListedIn` frontmatter adds; pagination skips these. */
const CROSS_LISTED_ATTR = 'data-cross-listed';

/** A docs file's directory as a URL path, e.g. `Users Guide/03.Models/x.mdx` -> `users-guide/models`. */
const fileDirectory = (filePath: string | undefined) => {
  const relative = filePath?.split('content/docs/').pop() ?? '';
  const directory = relative.slice(0, Math.max(relative.lastIndexOf('/'), 0));
  // A placeholder file name, because generateDocsId drops a trailing extension-like segment.
  return directory ? parentDirectory(generateDocsId({ entry: `${directory}/page.md`, data: {} })) : '';
};

const getDocsIndex = async () => {
  const docs = await getCollection('docs');
  return {
    /** Maps each docs page id to its file name, which keeps the sorting prefix the id drops. */
    fileNames: new Map(docs.map((doc) => [doc.id, doc.filePath?.split('/').pop() ?? ''])),
    /** Maps each docs page id to its file's directory, which a custom slug or an index page's id does not show. */
    directories: new Map(docs.map((doc) => [doc.id, fileDirectory(doc.filePath)])),
    // Starlight leaves draft (in production) and hidden pages out of the sidebar, so there is nothing to copy.
    crossListings: docs
      .filter((doc) => !doc.data.sidebar.hidden && !(doc.data.draft && import.meta.env.PROD))
      .flatMap((doc): CrossListing[] =>
        (doc.data.alsoListedIn ?? []).map((directory) => ({
          id: doc.id,
          directory: trimSlashes(directory),
        }))
      ),
  };
};

const hrefToId = (href: string) => {
  const path = trimSlashes(href);
  return basePath && path.startsWith(`${basePath}/`) ? path.slice(basePath.length + 1) : path;
};

/**
 * Starlight orders autogenerated entries by frontmatter `sidebar.order`, then by id, and ids no longer carry
 * the prefix. Reorder siblings generated from the same directory by prefix (unprefixed ones follow, in
 * Starlight's order) and strip the prefix from directory labels. Other entries keep their positions.
 */
const sortAndRelabel = (entries: SidebarEntry[], fileNames: Map<string, string>): boolean => {
  let changed = false;
  const sortKey = (entry: SidebarEntry) =>
    getSortPrefix(entry.type === 'group' ? entry.label : (fileNames.get(hrefToId(entry.href)) ?? '')) ??
    Number.POSITIVE_INFINITY;

  const slotsByDirectory = new Map<string, number[]>();
  entries.forEach((entry, index) => {
    const directory = 'autogenerate' in entry ? entry.autogenerate?.directory : undefined;
    if (directory !== undefined) slotsByDirectory.set(directory, [...(slotsByDirectory.get(directory) ?? []), index]);
  });
  for (const slots of slotsByDirectory.values()) {
    const sorted = slots.map((index) => entries[index]!).sort((a, b) => sortKey(a) - sortKey(b));
    slots.forEach((slot, i) => {
      if (entries[slot] !== sorted[i]) changed = true;
      entries[slot] = sorted[i]!;
    });
  }

  for (const entry of entries) {
    if (entry.type !== 'group') continue;
    if ('autogenerate' in entry && entry.autogenerate) entry.label = stripSortPrefix(entry.label);
    if (sortAndRelabel(entry.entries, fileNames)) changed = true;
  }
  return changed;
};

const flattenLinks = (entries: SidebarEntry[]): SidebarLink[] =>
  entries.flatMap((entry) => (entry.type === 'group' ? flattenLinks(entry.entries) : [entry]));

/**
 * The group autogenerated from a docs directory: the one whose own links are pages in that directory. A directory
 * holding only subdirectories cannot be found this way.
 */
const findDirectoryGroup = (
  entries: SidebarEntry[],
  directory: string,
  directories: Map<string, string>
): SidebarEntry[] | undefined => {
  if (entries.some((entry) => entry.type === 'link' && directories.get(hrefToId(entry.href)) === directory)) {
    return entries;
  }
  for (const entry of entries) {
    const found = entry.type === 'group' ? findDirectoryGroup(entry.entries, directory, directories) : undefined;
    if (found) return found;
  }
  return undefined;
};

/**
 * Autogenerated sidebars list each page once, under its own directory. Add a copy of each cross-listed page's link
 * to the group of every directory its `alsoListedIn` frontmatter names, placed alphabetically by label among that
 * group's links (so target directories should order their pages alphabetically). A misconfigured listing fails the
 * build.
 */
const addCrossListings = (
  sidebar: SidebarEntry[],
  crossListings: CrossListing[],
  directories: Map<string, string>
): boolean => {
  if (crossListings.length === 0) return false;
  const linksById = new Map(flattenLinks(sidebar).map((link) => [hrefToId(link.href), link]));
  for (const { id, directory } of crossListings) {
    const link = linksById.get(id);
    if (!link) throw new Error(`Cross-listed page "${id}" has no sidebar link.`);
    if (directories.get(id) === directory) throw new Error(`Page "${id}" is cross-listed in its own directory.`);
    const group = findDirectoryGroup(sidebar, directory, directories);
    if (!group) {
      throw new Error(`Page "${id}" is cross-listed in "${directory}", which has no sidebar group with pages.`);
    }
    // Before the first link that sorts after it, else before the group's first subgroup, else last.
    const laterLink = group.findIndex(
      (entry) => entry.type === 'link' && entry.label.localeCompare(link.label, 'en', { sensitivity: 'base' }) > 0
    );
    const firstGroup = group.findIndex((entry) => entry.type === 'group');
    const index = laterLink !== -1 ? laterLink : firstGroup !== -1 ? firstGroup : group.length;
    // The page's own link carries the current-page state, so the copy never does.
    const copy: SidebarLink = {
      ...link,
      isCurrent: false,
      attrs: { ...link.attrs, [CROSS_LISTED_ATTR]: '' },
    };
    group.splice(index, 0, copy);
  }
  return true;
};

/** Mirrors Starlight's handling of the frontmatter `prev`/`next` options for a regenerated neighbour link. */
const applyPrevNextConfig = (link: SidebarLink | undefined, config: PrevNextConfig): SidebarLink | undefined => {
  if (config === false) return undefined;
  if (config === undefined || config === true) return link;
  if (typeof config === 'string') return link && { ...link, label: config };
  if (link) return { ...link, label: config.label ?? link.label, href: config.link ?? link.href, attrs: {} };
  if (config.link && config.label) {
    return { type: 'link', href: config.link, label: config.label, isCurrent: false, badge: undefined, attrs: {} };
  }
  return undefined;
};

export const onRequest = defineRouteMiddleware(async (context) => {
  const route = context.locals.starlightRoute;
  // Starlight hands each render its own copy of the sidebar.
  const { fileNames, directories, crossListings } = await getDocsIndex();
  const reordered = sortAndRelabel(route.sidebar, fileNames);
  const crossListed = addCrossListings(route.sidebar, crossListings, directories);
  if (!reordered && !crossListed) return;

  // Starlight derived prev/next links before the reorder. This site keeps the default `pagination: true`.
  const links = flattenLinks(route.sidebar).filter((link) => !(CROSS_LISTED_ATTR in link.attrs));
  const current = links.findIndex((link) => link.isCurrent);
  if (current === -1) return;
  const { data } = route.entry;
  route.pagination.prev = applyPrevNextConfig(links[current - 1], data.prev);
  route.pagination.next = applyPrevNextConfig(links[current + 1], data.next);
});
