"""Representative key layout of a kohya (sd-scripts) Krea-2 LoRA.

Captured from `Krea2_Don-Martin_LoRA-step00001200.safetensors` (metadata: `ss_base_model_version=krea2`,
`ss_network_dim=32`, `ss_network_alpha=32`). The full adapter has 264 modules / 792 tensors covering all 28
transformer blocks and both text-fusion stages; this fixture keeps the first and last transformer block, one
layerwise and one refiner text-fusion block, and every top-level module.

kohya flattens the module path (`path.replace(".", "_")`) and prefixes it with `lora_unet_`, over the native
(ComfyUI) module names - so `lora_unet_blocks_6_attn_wv` denotes `transformer_blocks.6.attn.to_v`.
"""

state_dict_keys: dict[str, list[int]] = {
    "lora_unet_blocks_0_attn_gate.alpha": [],
    "lora_unet_blocks_0_attn_gate.lora_down.weight": [32, 6144],
    "lora_unet_blocks_0_attn_gate.lora_up.weight": [6144, 32],
    "lora_unet_blocks_0_attn_wk.alpha": [],
    "lora_unet_blocks_0_attn_wk.lora_down.weight": [32, 6144],
    "lora_unet_blocks_0_attn_wk.lora_up.weight": [1536, 32],
    "lora_unet_blocks_0_attn_wo.alpha": [],
    "lora_unet_blocks_0_attn_wo.lora_down.weight": [32, 6144],
    "lora_unet_blocks_0_attn_wo.lora_up.weight": [6144, 32],
    "lora_unet_blocks_0_attn_wq.alpha": [],
    "lora_unet_blocks_0_attn_wq.lora_down.weight": [32, 6144],
    "lora_unet_blocks_0_attn_wq.lora_up.weight": [6144, 32],
    "lora_unet_blocks_0_attn_wv.alpha": [],
    "lora_unet_blocks_0_attn_wv.lora_down.weight": [32, 6144],
    "lora_unet_blocks_0_attn_wv.lora_up.weight": [1536, 32],
    "lora_unet_blocks_0_mlp_down.alpha": [],
    "lora_unet_blocks_0_mlp_down.lora_down.weight": [32, 16384],
    "lora_unet_blocks_0_mlp_down.lora_up.weight": [6144, 32],
    "lora_unet_blocks_0_mlp_gate.alpha": [],
    "lora_unet_blocks_0_mlp_gate.lora_down.weight": [32, 6144],
    "lora_unet_blocks_0_mlp_gate.lora_up.weight": [16384, 32],
    "lora_unet_blocks_0_mlp_up.alpha": [],
    "lora_unet_blocks_0_mlp_up.lora_down.weight": [32, 6144],
    "lora_unet_blocks_0_mlp_up.lora_up.weight": [16384, 32],
    "lora_unet_blocks_27_attn_gate.alpha": [],
    "lora_unet_blocks_27_attn_gate.lora_down.weight": [32, 6144],
    "lora_unet_blocks_27_attn_gate.lora_up.weight": [6144, 32],
    "lora_unet_blocks_27_attn_wk.alpha": [],
    "lora_unet_blocks_27_attn_wk.lora_down.weight": [32, 6144],
    "lora_unet_blocks_27_attn_wk.lora_up.weight": [1536, 32],
    "lora_unet_blocks_27_attn_wo.alpha": [],
    "lora_unet_blocks_27_attn_wo.lora_down.weight": [32, 6144],
    "lora_unet_blocks_27_attn_wo.lora_up.weight": [6144, 32],
    "lora_unet_blocks_27_attn_wq.alpha": [],
    "lora_unet_blocks_27_attn_wq.lora_down.weight": [32, 6144],
    "lora_unet_blocks_27_attn_wq.lora_up.weight": [6144, 32],
    "lora_unet_blocks_27_attn_wv.alpha": [],
    "lora_unet_blocks_27_attn_wv.lora_down.weight": [32, 6144],
    "lora_unet_blocks_27_attn_wv.lora_up.weight": [1536, 32],
    "lora_unet_blocks_27_mlp_down.alpha": [],
    "lora_unet_blocks_27_mlp_down.lora_down.weight": [32, 16384],
    "lora_unet_blocks_27_mlp_down.lora_up.weight": [6144, 32],
    "lora_unet_blocks_27_mlp_gate.alpha": [],
    "lora_unet_blocks_27_mlp_gate.lora_down.weight": [32, 6144],
    "lora_unet_blocks_27_mlp_gate.lora_up.weight": [16384, 32],
    "lora_unet_blocks_27_mlp_up.alpha": [],
    "lora_unet_blocks_27_mlp_up.lora_down.weight": [32, 6144],
    "lora_unet_blocks_27_mlp_up.lora_up.weight": [16384, 32],
    "lora_unet_first.alpha": [],
    "lora_unet_first.lora_down.weight": [32, 64],
    "lora_unet_first.lora_up.weight": [6144, 32],
    "lora_unet_last_linear.alpha": [],
    "lora_unet_last_linear.lora_down.weight": [32, 6144],
    "lora_unet_last_linear.lora_up.weight": [64, 32],
    "lora_unet_tmlp_0.alpha": [],
    "lora_unet_tmlp_0.lora_down.weight": [32, 256],
    "lora_unet_tmlp_0.lora_up.weight": [6144, 32],
    "lora_unet_tmlp_2.alpha": [],
    "lora_unet_tmlp_2.lora_down.weight": [32, 6144],
    "lora_unet_tmlp_2.lora_up.weight": [6144, 32],
    "lora_unet_tproj_1.alpha": [],
    "lora_unet_tproj_1.lora_down.weight": [32, 6144],
    "lora_unet_tproj_1.lora_up.weight": [36864, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_gate.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_gate.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_gate.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wk.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wk.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wk.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wo.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wo.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wo.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wq.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wq.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wq.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wv.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wv.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_layerwise_blocks_0_attn_wv.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_down.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_down.lora_down.weight": [32, 6912],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_down.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_gate.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_gate.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_gate.lora_up.weight": [6912, 32],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_up.alpha": [],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_up.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_layerwise_blocks_0_mlp_up.lora_up.weight": [6912, 32],
    "lora_unet_txtfusion_projector.alpha": [],
    "lora_unet_txtfusion_projector.lora_down.weight": [32, 12],
    "lora_unet_txtfusion_projector.lora_up.weight": [1, 32],
    "lora_unet_txtfusion_refiner_blocks_1_attn_gate.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_attn_gate.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_refiner_blocks_1_attn_gate.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wk.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wk.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wk.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wo.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wo.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wo.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wq.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wq.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wq.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wv.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wv.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_refiner_blocks_1_attn_wv.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_down.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_down.lora_down.weight": [32, 6912],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_down.lora_up.weight": [2560, 32],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_gate.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_gate.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_gate.lora_up.weight": [6912, 32],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_up.alpha": [],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_up.lora_down.weight": [32, 2560],
    "lora_unet_txtfusion_refiner_blocks_1_mlp_up.lora_up.weight": [6912, 32],
    "lora_unet_txtmlp_1.alpha": [],
    "lora_unet_txtmlp_1.lora_down.weight": [32, 2560],
    "lora_unet_txtmlp_1.lora_up.weight": [6144, 32],
    "lora_unet_txtmlp_3.alpha": [],
    "lora_unet_txtmlp_3.lora_down.weight": [32, 6144],
    "lora_unet_txtmlp_3.lora_up.weight": [6144, 32],
}
