from pathlib import PureWindowsPath

_CONTROL_CHARS = frozenset(chr(c) for c in range(0x20)) | {"\x7f"}


def is_plain_filename(name: str) -> bool:
    r"""Checks whether a name is safe to join onto a storage directory.

    Names that identify a stored file - object serializer names, model keys, image names - are generated by the
    server, but they travel out to the client and come back as request parameters or node inputs, so on the way in
    they are untrusted. Joining one onto a directory is only safe if it is a bare filename: anything carrying a
    separator, a drive letter or a `..` would resolve outside that directory.

    Three details are worth spelling out:

    - `PureWindowsPath` is used for the check rather than the platform's `Path`. It treats both `/` and `\` as
      separators and understands drive letters, so backslash- and drive-shaped payloads are rejected on posix too,
      instead of passing here and only escaping on Windows deployments.
    - Trailing dots and spaces are stripped before the `.`/`..` comparison. `pathlib` keeps them, but the Win32
      path normaliser drops them from the final component when the file is opened, so `".. "` would reach the
      parent directory on Windows.
    - Control characters are rejected outright. They cannot escape a directory on their own, but a name is only
      "safe to join" if it also survives being put in a header or a log line.
    """
    if not name or _CONTROL_CHARS.intersection(name):
        return False
    if name.rstrip(" .") in ("", ".", ".."):
        return False
    return PureWindowsPath(name).name == name
