"""
InvokeAI custom nodes initialization

This file is responsible for loading all custom nodes from this directory.

All python files are loaded on app startup. Custom nodes will be initialized and available for use
in workflows.

The app must be restarted for changes to be picked up.

This file is overwritten on launch. Do not edit this file directly.
"""
import sys
from importlib import import_module
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path

from invokeai.backend.util.logging import InvokeAILogger

logger = InvokeAILogger.get_logger()
count = 0
for f in Path(__file__).parent.rglob("*.py"):
    module_name = f.stem
    if (not module_name.startswith("_")) and (module_name not in globals()):
        spec = spec_from_file_location(module_name, f.absolute())
        if spec is None or spec.loader is None:
            logger.warn(f"Could not load {f}")
            continue
        module = module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        count += 1
    del f, module_name

logger.info(f"Loaded {count} modules from {Path(__file__).parent}")

del import_module, Path
