"""Compatibility support for invocation modules moved into subpackages."""

import importlib
import logging
import sys
from types import ModuleType

LEGACY_MODULE_MAP: dict[str, str] = {
    "invokeai.app.invocations.anima_denoise": "invokeai.app.invocations.anima.anima_denoise",
    "invokeai.app.invocations.anima_lllite": "invokeai.app.invocations.anima.anima_lllite",
    "invokeai.app.invocations.anima_lora_loader": "invokeai.app.invocations.anima.anima_lora_loader",
    "invokeai.app.invocations.anima_model_loader": "invokeai.app.invocations.anima.anima_model_loader",
    "invokeai.app.invocations.cogview4_denoise": "invokeai.app.invocations.cogview4.cogview4_denoise",
    "invokeai.app.invocations.cogview4_model_loader": "invokeai.app.invocations.cogview4.cogview4_model_loader",
    "invokeai.app.invocations.ernie_image_denoise": "invokeai.app.invocations.ernie_image.ernie_image_denoise",
    "invokeai.app.invocations.ernie_image_model_loader": "invokeai.app.invocations.ernie_image.ernie_image_model_loader",
    "invokeai.app.invocations.ernie_image_prompt_enhancer": "invokeai.app.invocations.ernie_image.ernie_image_prompt_enhancer",
    "invokeai.app.invocations.flux_control_lora_loader": "invokeai.app.invocations.flux.flux_control_lora_loader",
    "invokeai.app.invocations.flux_controlnet": "invokeai.app.invocations.flux.flux_controlnet",
    "invokeai.app.invocations.flux_denoise": "invokeai.app.invocations.flux.flux_denoise",
    "invokeai.app.invocations.flux_fill": "invokeai.app.invocations.flux.flux_fill",
    "invokeai.app.invocations.flux_ip_adapter": "invokeai.app.invocations.flux.flux_ip_adapter",
    "invokeai.app.invocations.flux_kontext": "invokeai.app.invocations.flux.flux_kontext",
    "invokeai.app.invocations.flux_lora_loader": "invokeai.app.invocations.flux.flux_lora_loader",
    "invokeai.app.invocations.flux_model_loader": "invokeai.app.invocations.flux.flux_model_loader",
    "invokeai.app.invocations.flux_redux": "invokeai.app.invocations.flux.flux_redux",
    "invokeai.app.invocations.flux2_denoise": "invokeai.app.invocations.flux2.flux2_denoise",
    "invokeai.app.invocations.flux2_dev_lora_loader": "invokeai.app.invocations.flux2.flux2_dev_lora_loader",
    "invokeai.app.invocations.flux2_dev_model_loader": "invokeai.app.invocations.flux2.flux2_dev_model_loader",
    "invokeai.app.invocations.flux2_klein_lora_loader": "invokeai.app.invocations.flux2.flux2_klein_lora_loader",
    "invokeai.app.invocations.flux2_klein_model_loader": "invokeai.app.invocations.flux2.flux2_klein_model_loader",
    "invokeai.app.invocations.ideogram4_caption": "invokeai.app.invocations.ideogram4.ideogram4_caption",
    "invokeai.app.invocations.ideogram4_denoise": "invokeai.app.invocations.ideogram4.ideogram4_denoise",
    "invokeai.app.invocations.ideogram4_model_loader": "invokeai.app.invocations.ideogram4.ideogram4_model_loader",
    "invokeai.app.invocations.krea2_conditioning_rebalance": "invokeai.app.invocations.krea2.krea2_conditioning_rebalance",
    "invokeai.app.invocations.krea2_denoise": "invokeai.app.invocations.krea2.krea2_denoise",
    "invokeai.app.invocations.krea2_lora_loader": "invokeai.app.invocations.krea2.krea2_lora_loader",
    "invokeai.app.invocations.krea2_model_loader": "invokeai.app.invocations.krea2.krea2_model_loader",
    "invokeai.app.invocations.krea2_seed_variance": "invokeai.app.invocations.krea2.krea2_seed_variance",
    "invokeai.app.invocations.minimax_h3_denoise": "invokeai.app.invocations.minimax_h3.minimax_h3_denoise",
    "invokeai.app.invocations.minimax_h3_frame_conditioning": "invokeai.app.invocations.minimax_h3.minimax_h3_frame_conditioning",
    "invokeai.app.invocations.minimax_h3_ideal_dimensions": "invokeai.app.invocations.minimax_h3.minimax_h3_ideal_dimensions",
    "invokeai.app.invocations.minimax_h3_lora_loader": "invokeai.app.invocations.minimax_h3.minimax_h3_lora_loader",
    "invokeai.app.invocations.minimax_h3_model_loader": "invokeai.app.invocations.minimax_h3.minimax_h3_model_loader",
    "invokeai.app.invocations.flux2_pid_decode": "invokeai.app.invocations.pid.flux2_pid_decode",
    "invokeai.app.invocations.flux_pid_decode": "invokeai.app.invocations.pid.flux_pid_decode",
    "invokeai.app.invocations.pid_decoder_loader": "invokeai.app.invocations.pid.pid_decoder_loader",
    "invokeai.app.invocations.pid_upscale": "invokeai.app.invocations.pid.pid_upscale",
    "invokeai.app.invocations.qwen_image_pid_decode": "invokeai.app.invocations.pid.qwen_image_pid_decode",
    "invokeai.app.invocations.sd3_pid_decode": "invokeai.app.invocations.pid.sd3_pid_decode",
    "invokeai.app.invocations.sdxl_pid_decode": "invokeai.app.invocations.pid.sdxl_pid_decode",
    "invokeai.app.invocations.z_image_pid_decode": "invokeai.app.invocations.pid.z_image_pid_decode",
    "invokeai.app.invocations.qwen_image_denoise": "invokeai.app.invocations.qwen_image.qwen_image_denoise",
    "invokeai.app.invocations.qwen_image_lora_loader": "invokeai.app.invocations.qwen_image.qwen_image_lora_loader",
    "invokeai.app.invocations.qwen_image_model_loader": "invokeai.app.invocations.qwen_image.qwen_image_model_loader",
    "invokeai.app.invocations.controlnet": "invokeai.app.invocations.sd.controlnet",
    "invokeai.app.invocations.create_denoise_mask": "invokeai.app.invocations.sd.create_denoise_mask",
    "invokeai.app.invocations.create_gradient_mask": "invokeai.app.invocations.sd.create_gradient_mask",
    "invokeai.app.invocations.denoise_latents": "invokeai.app.invocations.sd.denoise_latents",
    "invokeai.app.invocations.ip_adapter": "invokeai.app.invocations.sd.ip_adapter",
    "invokeai.app.invocations.sdxl": "invokeai.app.invocations.sd.sdxl",
    "invokeai.app.invocations.t2i_adapter": "invokeai.app.invocations.sd.t2i_adapter",
    "invokeai.app.invocations.tiled_multi_diffusion_denoise_latents": "invokeai.app.invocations.sd.tiled_multi_diffusion_denoise_latents",
    "invokeai.app.invocations.sd3_denoise": "invokeai.app.invocations.sd3.sd3_denoise",
    "invokeai.app.invocations.sd3_model_loader": "invokeai.app.invocations.sd3.sd3_model_loader",
    "invokeai.app.invocations.anima_text_encoder": "invokeai.app.invocations.text_encoder.anima_text_encoder",
    "invokeai.app.invocations.cogview4_text_encoder": "invokeai.app.invocations.text_encoder.cogview4_text_encoder",
    "invokeai.app.invocations.compel": "invokeai.app.invocations.text_encoder.compel",
    "invokeai.app.invocations.ernie_image_text_encoder": "invokeai.app.invocations.text_encoder.ernie_image_text_encoder",
    "invokeai.app.invocations.flux2_dev_text_encoder": "invokeai.app.invocations.text_encoder.flux2_dev_text_encoder",
    "invokeai.app.invocations.flux2_klein_text_encoder": "invokeai.app.invocations.text_encoder.flux2_klein_text_encoder",
    "invokeai.app.invocations.flux_text_encoder": "invokeai.app.invocations.text_encoder.flux_text_encoder",
    "invokeai.app.invocations.gemma2_encoder_loader": "invokeai.app.invocations.text_encoder.gemma2_encoder_loader",
    "invokeai.app.invocations.ideogram4_text_encoder": "invokeai.app.invocations.text_encoder.ideogram4_text_encoder",
    "invokeai.app.invocations.krea2_text_encoder": "invokeai.app.invocations.text_encoder.krea2_text_encoder",
    "invokeai.app.invocations.minimax_h3_text_encoder": "invokeai.app.invocations.text_encoder.minimax_h3_text_encoder",
    "invokeai.app.invocations.qwen_image_text_encoder": "invokeai.app.invocations.text_encoder.qwen_image_text_encoder",
    "invokeai.app.invocations.sd3_text_encoder": "invokeai.app.invocations.text_encoder.sd3_text_encoder",
    "invokeai.app.invocations.wan_text_encoder": "invokeai.app.invocations.text_encoder.wan_text_encoder",
    "invokeai.app.invocations.z_image_text_encoder": "invokeai.app.invocations.text_encoder.z_image_text_encoder",
    "invokeai.app.invocations.anima_image_to_latents": "invokeai.app.invocations.vae.anima_image_to_latents",
    "invokeai.app.invocations.anima_latents_to_image": "invokeai.app.invocations.vae.anima_latents_to_image",
    "invokeai.app.invocations.cogview4_image_to_latents": "invokeai.app.invocations.vae.cogview4_image_to_latents",
    "invokeai.app.invocations.cogview4_latents_to_image": "invokeai.app.invocations.vae.cogview4_latents_to_image",
    "invokeai.app.invocations.ernie_image_vae_decode": "invokeai.app.invocations.vae.ernie_image_vae_decode",
    "invokeai.app.invocations.flux2_vae_decode": "invokeai.app.invocations.vae.flux2_vae_decode",
    "invokeai.app.invocations.flux2_vae_encode": "invokeai.app.invocations.vae.flux2_vae_encode",
    "invokeai.app.invocations.flux_vae_decode": "invokeai.app.invocations.vae.flux_vae_decode",
    "invokeai.app.invocations.flux_vae_encode": "invokeai.app.invocations.vae.flux_vae_encode",
    "invokeai.app.invocations.ideogram4_latents_to_image": "invokeai.app.invocations.vae.ideogram4_latents_to_image",
    "invokeai.app.invocations.image_to_latents": "invokeai.app.invocations.vae.image_to_latents",
    "invokeai.app.invocations.latents_to_image": "invokeai.app.invocations.vae.latents_to_image",
    "invokeai.app.invocations.minimax_h3_latents_to_image": "invokeai.app.invocations.vae.minimax_h3_latents_to_image",
    "invokeai.app.invocations.minimax_h3_latents_to_video": "invokeai.app.invocations.vae.minimax_h3_latents_to_video",
    "invokeai.app.invocations.qwen_image_image_to_latents": "invokeai.app.invocations.vae.qwen_image_image_to_latents",
    "invokeai.app.invocations.qwen_image_latents_to_image": "invokeai.app.invocations.vae.qwen_image_latents_to_image",
    "invokeai.app.invocations.sd3_image_to_latents": "invokeai.app.invocations.vae.sd3_image_to_latents",
    "invokeai.app.invocations.sd3_latents_to_image": "invokeai.app.invocations.vae.sd3_latents_to_image",
    "invokeai.app.invocations.wan_image_to_latents": "invokeai.app.invocations.vae.wan_image_to_latents",
    "invokeai.app.invocations.wan_latents_to_image": "invokeai.app.invocations.vae.wan_latents_to_image",
    "invokeai.app.invocations.wan_latents_to_video": "invokeai.app.invocations.vae.wan_latents_to_video",
    "invokeai.app.invocations.z_image_image_to_latents": "invokeai.app.invocations.vae.z_image_image_to_latents",
    "invokeai.app.invocations.z_image_latents_to_image": "invokeai.app.invocations.vae.z_image_latents_to_image",
    "invokeai.app.invocations.wan_denoise": "invokeai.app.invocations.wan.wan_denoise",
    "invokeai.app.invocations.wan_ideal_dimensions": "invokeai.app.invocations.wan.wan_ideal_dimensions",
    "invokeai.app.invocations.wan_lora_loader": "invokeai.app.invocations.wan.wan_lora_loader",
    "invokeai.app.invocations.wan_model_loader": "invokeai.app.invocations.wan.wan_model_loader",
    "invokeai.app.invocations.wan_ref_image_encoder": "invokeai.app.invocations.wan.wan_ref_image_encoder",
    "invokeai.app.invocations.wan_video_denoise": "invokeai.app.invocations.wan.wan_video_denoise",
    "invokeai.app.invocations.z_image_control": "invokeai.app.invocations.z_image.z_image_control",
    "invokeai.app.invocations.z_image_denoise": "invokeai.app.invocations.z_image.z_image_denoise",
    "invokeai.app.invocations.z_image_lora_loader": "invokeai.app.invocations.z_image.z_image_lora_loader",
    "invokeai.app.invocations.z_image_model_loader": "invokeai.app.invocations.z_image.z_image_model_loader",
    "invokeai.app.invocations.z_image_seed_variance_enhancer": "invokeai.app.invocations.z_image.z_image_seed_variance_enhancer",
}


def forward_legacy_module(legacy_name: str, canonical_name: str) -> ModuleType:
    module = importlib.import_module(canonical_name)
    logging.getLogger("InvokeAI").info("Legacy invocation module %s moved to %s", legacy_name, canonical_name)
    sys.modules[legacy_name] = module
    return module
