import type { AstroConfig } from 'astro';

type RedirectsConfig = AstroConfig['redirects'];

const redirects: RedirectsConfig = {
  '/CODE_OF_CONDUCT': '/contributing/code-of-conduct',
  '/RELEASE': '/development/process/release-process',
  '/installation': '/start-here/installation',
  '/installation/docker': '/configuration/docker',
  '/installation/manual': '/start-here/manual',
  '/installation/models': '/users-guide/models/introduction',
  '/installation/patchmatch': '/configuration/optimization/patchmatch',
  '/installation/quick_start': '/start-here/installation',
  '/installation/requirements': '/start-here/system-requirements',
  '/configuration': '/configuration/invokeai-yaml',
  '/features/low-vram/': '/configuration/optimization/low-vram-mode/',
  '/features/lasso-tool': '/users-guide/canvas/canvas-guide',
  '/features/shapes-tool': '/users-guide/canvas/canvas-guide',
  '/features/video-generation': '/users-guide/video-generation/introduction',
  '/faq': '/troubleshooting/faq',
  '/help/SAMPLER_CONVERGENCE': '/users-guide/image-generation/parameters',
  '/help/diffusion': '/users-guide/image-generation/advanced-topics/diffusion',
  '/help/gettingStartedWithAI': '/users-guide/image-generation/image-generation',
  '/nodes/NODES': '/users-guide/workflows/introduction',
  '/nodes/NODES_MIGRATION_V3_V4': '/development/guides/api-development',
  '/nodes/comfyToInvoke': '/users-guide/workflows/comfyui-migration',
  '/nodes/communityNodes': '/users-guide/workflows/community-nodes',
  '/nodes/contributingNodes': '/development/guides/creating-nodes',
  '/nodes/detailedNodes/faceTools': '/users-guide/workflows/face-tools',
  '/nodes/invocation-api': '/development/guides/api-development',
  '/contributing/ARCHITECTURE': '/development/architecture/overview',
  '/contributing/DOWNLOAD_QUEUE': '/development/architecture/model-manager',
  '/contributing/HOTKEYS': '/users-guide/workbench/hotkeys',
  '/contributing/INVOCATIONS': '/development/architecture/invocations',
  '/contributing/LOCAL_DEVELOPMENT': '/development/setup/dev-environment',
  '/contributing/MODEL_MANAGER': '/development/architecture/model-manager',
  '/contributing/NEW_MODEL_INTEGRATION': '/development/guides/models',
  '/contributing/PR-MERGE-POLICY': '/development/process/pr-merge-policy',
  '/contributing/TESTS': '/development/guides/tests',
  '/contributing/contribution_guides/development': '/development',
  '/contributing/contribution_guides/newContributorChecklist':
    '/contributing/new-contributor-guide',
  '/contributing/dev-environment': '/development/setup/dev-environment',
  '/contributing/frontend': '/development/front-end',
  '/contributing/frontend/state-management':
    '/development/front-end/state-management',
  '/contributing/frontend/workflows': '/development/front-end/workflows',
  // Pages moved by the v7 documentation reorganization.
  '/concepts/diffusion': '/users-guide/image-generation/advanced-topics/diffusion',
  '/concepts/dynamic-prompting': '/users-guide/image-generation/prompting-guide',
  '/concepts/image-generation': '/users-guide/image-generation/image-generation',
  '/concepts/models': '/users-guide/models/introduction',
  '/concepts/nodes-workflows': '/users-guide/workflows/introduction',
  '/concepts/parameters': '/users-guide/image-generation/parameters',
  '/concepts/prompt-syntax': '/users-guide/image-generation/prompting-guide',
  '/concepts/prompting-guide': '/users-guide/image-generation/prompting-guide',
  '/concepts/video-generation': '/users-guide/video-generation/introduction',
  '/configuration/fp8-storage': '/configuration/optimization/fp8-storage',
  '/configuration/low-vram-mode': '/configuration/optimization/low-vram-mode',
  '/configuration/patchmatch': '/configuration/optimization/patchmatch',
  '/configuration/sdnq-quantization': '/configuration/optimization/sdnq-quantization',
  '/features/canvas/bounding-box': '/users-guide/canvas/canvas-guide',
  '/features/canvas/canvas-projects': '/users-guide/projects/introduction',
  '/features/canvas/gradient-tool': '/users-guide/canvas/canvas-guide',
  '/features/canvas/lasso-tool': '/users-guide/canvas/canvas-guide',
  '/features/canvas/layers-and-drops': '/users-guide/canvas/introduction',
  '/features/canvas/run-workflow': '/users-guide/canvas/canvas-guide',
  '/features/canvas/shapes-tool': '/users-guide/canvas/canvas-guide',
  '/features/canvas/text-tool': '/users-guide/canvas/canvas-guide',
  '/features/custom-node-manager': '/users-guide/workflows/custom-node-manager',
  '/features/external-models': '/users-guide/models/external-models/introduction',
  '/features/external-models/alibabacloud': '/users-guide/models/external-models/alibabacloud',
  '/features/external-models/gemini': '/users-guide/models/external-models/gemini',
  '/features/external-models/openai': '/users-guide/models/external-models/openai',
  '/features/external-models/seedream': '/users-guide/models/external-models/seedream',
  '/features/gallery': '/users-guide/gallery/introduction',
  '/features/hidiffusion': '/users-guide/image-generation/advanced-topics/hidiffusion',
  '/features/hotkeys': '/users-guide/workbench/hotkeys',
  '/features/image-storage-maintenance': '/users-guide/gallery/image-storage-maintenance',
  '/features/intermediates': '/users-guide/image-generation/intermediates',
  '/features/krea-2': '/users-guide/models/local-models/krea-2',
  '/features/multi-user-mode/admin-guide': '/configuration/multi-user-mode/admin-guide',
  '/features/multi-user-mode/api-guide': '/configuration/multi-user-mode/api-guide',
  '/features/multi-user-mode/user-guide': '/configuration/multi-user-mode/user-guide',
  '/features/pid-decode': '/users-guide/image-generation/advanced-topics/pid-decode',
  '/features/prompt-tools': '/users-guide/image-generation/prompt-tools',
  '/features/video-workflows': '/users-guide/video-generation/video-workflows',
  '/features/workflows': '/users-guide/workflows/introduction',
  '/features/workflows/adding-nodes': '/users-guide/workflows/introduction',
  '/features/workflows/comfyui-migration': '/users-guide/workflows/comfyui-migration',
  '/features/workflows/community-nodes': '/users-guide/workflows/community-nodes',
  '/features/workflows/custom-node-manager': '/users-guide/workflows/custom-node-manager',
  '/features/workflows/editor-interface': '/users-guide/workflows/introduction',
  '/features/workflows/face-tools': '/users-guide/workflows/face-tools',
  '/features/workflows/loop-nodes': '/users-guide/workflows/loop-nodes',
};

function createRedirects(base: string): RedirectsConfig {
  return Object.fromEntries(
    Object.entries(redirects).map(([from, to]) => [from, base + to]),
  );
}

export { createRedirects };
