/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Core generation metadata for an image/tensor generated in InvokeAI.
 *
 * Also includes any metadata from the image's PNG tEXt chunks.
 *
 * Generated by traversing the execution graph, collecting the parameters of the nearest ancestors of a given node.
 *
 * Full metadata may be accessed by querying for the session in the `graph_executions` table.
 */
export type ImageMetadata = {
  /**
   * The positive conditioning.
   */
  positive_conditioning?: string;
  /**
   * The negative conditioning.
   */
  negative_conditioning?: string;
  /**
   * Width of the image/tensor in pixels.
   */
  width?: number;
  /**
   * Height of the image/tensor in pixels.
   */
  height?: number;
  /**
   * The seed used for noise generation.
   */
  seed?: number;
  /**
   * The classifier-free guidance scale.
   */
  cfg_scale?: number;
  /**
   * The number of steps used for inference.
   */
  steps?: number;
  /**
   * The scheduler used for inference.
   */
  scheduler?: string;
  /**
   * The model used for inference.
   */
  model?: string;
  /**
   * The strength used for image-to-image/tensor-to-tensor.
   */
  strength?: number;
  /**
   * The ID of the initial image.
   */
  image?: string;
  /**
   * The ID of the initial tensor.
   */
  tensor?: string;
  /**
   * Extra metadata, extracted from the PNG tEXt chunk.
   */
  extra?: string;
};

