name: 🐞 Bug Report

description: File a bug report

title: '[bug]: '

labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Bug Report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this problem?
      description: |
        Please [search](https://github.com/invoke-ai/InvokeAI/issues) first to see if an issue already exists for the problem.
      options:
        - label: I have searched the existing issues
          required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Install method
      description: How did you install Invoke?
      multiple: false
      options:
        - "Invoke's Launcher"
        - 'Stability Matrix'
        - 'Pinokio'
        - 'Manual'
    validations:
      required: true

  - type: markdown
    attributes:
      value: __Describe your environment__

  - type: dropdown
    id: os_dropdown
    attributes:
      label: Operating system
      description: Your computer's operating system.
      multiple: false
      options:
        - 'Linux'
        - 'Windows'
        - 'macOS'
        - 'other'
    validations:
      required: true

  - type: dropdown
    id: gpu_dropdown
    attributes:
      label: GPU vendor
      description: Your GPU's vendor.
      multiple: false
      options:
        - 'Nvidia (CUDA)'
        - 'AMD (ROCm)'
        - 'Apple Silicon (MPS)'
        - 'None (CPU)'
    validations:
      required: true

  - type: input
    id: gpu_model
    attributes:
      label: GPU model
      description: Your GPU's model. If on Apple Silicon, this is your Mac's chip. Leave blank if on CPU.
      placeholder: ex. RTX 2080 Ti, Mac M1 Pro
    validations:
      required: false

  - type: input
    id: vram
    attributes:
      label: GPU VRAM
      description: Your GPU's VRAM. If on Apple Silicon, this is your Mac's unified memory. Leave blank if on CPU.
      placeholder: 8GB
    validations:
      required: false

  - type: input
    id: version-number
    attributes:
      label: Version number
      description: |
        The version of Invoke you have installed. If it is not the [latest version](https://github.com/invoke-ai/InvokeAI/releases/latest), please update and try again to confirm the issue still exists. If you are testing main, please include the commit hash instead.
      placeholder: ex. v6.0.2
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser
      description: Your web browser and version, if you do not use the Launcher's provided GUI.
      placeholder: ex. Firefox 123.0b3
    validations:
      required: false

  - type: textarea
    id: python-deps
    attributes:
      label: System Information
      description: |
        Click the gear icon at the bottom left corner, then click "About". Click the copy button and then paste here.
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: |
        Describe what happened. Include any relevant error messages, stack traces and screenshots here.
      placeholder: I clicked button X and then Y happened.
    validations:
      required: true

  - type: textarea
    id: what-you-expected
    attributes:
      label: What you expected to happen
      description: Describe what you expected to happen.
      placeholder: I expected Z to happen.
    validations:
      required: true

  - type: textarea
    id: how-to-repro
    attributes:
      label: How to reproduce the problem
      description: List steps to reproduce the problem.
      placeholder: Start the app, generate an image with these settings, then click button X.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context that might help us to understand the problem.
      placeholder: Only happens when there is full moon and Friday the 13th on Christmas Eve 🎅🏻
    validations:
      required: false

  - type: input
    id: discord-username
    attributes:
      label: Discord username
      description: If you are on the Invoke discord and would prefer to be contacted there, please provide your username.
      placeholder: supercoolusername123
    validations:
      required: false
