export type InvokeAIThemeColors = {
  base: Partial<InvokeAIPaletteSteps>;
  baseAlpha: Partial<InvokeAIPaletteSteps>;
  gold: Partial<InvokeAIPaletteSteps>;
  goldAlpha: Partial<InvokeAIPaletteSteps>;
  working: Partial<InvokeAIPaletteSteps>;
  workingAlpha: Partial<InvokeAIPaletteSteps>;
  warning: Partial<InvokeAIPaletteSteps>;
  warningAlpha: Partial<InvokeAIPaletteSteps>;
  ok: Partial<InvokeAIPaletteSteps>;
  okAlpha: Partial<InvokeAIPaletteSteps>;
  error: Partial<InvokeAIPaletteSteps>;
  errorAlpha: Partial<InvokeAIPaletteSteps>;
  invokeYellow: Partial<InvokeAIPaletteSteps>;
  invokeYellowAlpha: Partial<InvokeAIPaletteSteps>;
  invokeRed: Partial<InvokeAIPaletteSteps>;
  invokeRedAlpha: Partial<InvokeAIPaletteSteps>;
  invokeGreen: Partial<InvokeAIPaletteSteps>;
  invokeGreenAlpha: Partial<InvokeAIPaletteSteps>;
  invokeBlue: Partial<InvokeAIPaletteSteps>;
  invokeBlueAlpha: Partial<InvokeAIPaletteSteps>;
};

export type InvokeAIPaletteSteps = {
  0: string;
  50: string;
  100: string;
  150: string;
  200: string;
  250: string;
  300: string;
  350: string;
  400: string;
  450: string;
  500: string;
  550: string;
  600: string;
  650: string;
  700: string;
  750: string;
  800: string;
  850: string;
  900: string;
  950: string;
  1000: string;
};
