import type { HotkeyCategory, HotkeyDefinition } from './types';

const categoryScopes = {
  app: { kind: 'global' },
  canvas: { kind: 'widget', typeId: 'canvas' },
  gallery: { kind: 'widget', typeId: 'gallery' },
  viewer: { kind: 'widget', typeId: 'preview' },
  workflows: { kind: 'widget', typeId: 'workflow' },
} as const;

const implemented = new Set([
  'app.cancelQueueItem',
  'app.clearQueue',
  'app.focusPrompt',
  'app.invoke',
  'app.invokeFront',
  'app.promptHistoryNext',
  'app.promptHistoryPrev',
  'app.promptWeightDown',
  'app.promptWeightUp',
  'app.resetPanelLayout',
  'app.selectCanvasTab',
  'app.selectGenerateTab',
  'app.selectModelsTab',
  'app.selectQueueTab',
  'app.selectWorkflowsTab',
  'app.toggleLeftPanel',
  'app.togglePanels',
  'app.toggleRightPanel',
  'canvas.deleteSelected',
  'canvas.nextEntity',
  'canvas.prevEntity',
  'canvas.redo',
  'canvas.undo',
  'gallery.clearSelection',
  'gallery.deleteSelection',
  'gallery.galleryNavDown',
  'gallery.galleryNavDownAlt',
  'gallery.galleryNavLeft',
  'gallery.galleryNavLeftAlt',
  'gallery.galleryNavRight',
  'gallery.galleryNavRightAlt',
  'gallery.galleryNavUp',
  'gallery.galleryNavUpAlt',
  'gallery.remix',
  'gallery.selectAllOnPage',
  'gallery.starImage',
  'viewer.nextComparisonMode',
  'viewer.deleteImage',
  'viewer.recallAll',
  'viewer.recallPrompts',
  'viewer.recallSeed',
  'viewer.remix',
  'viewer.swapImages',
  'viewer.toggleViewer',
  'viewer.useSize',
  'workflows.addNode',
  'workflows.copySelection',
  'workflows.deleteSelection',
  'workflows.pasteSelection',
  'workflows.pasteSelectionWithEdges',
  'workflows.redo',
  'workflows.selectAll',
  'workflows.undo',
]);

const editableAppHotkeys = new Set([
  'app.focusPrompt',
  'app.invoke',
  'app.invokeFront',
  'app.promptHistoryNext',
  'app.promptHistoryPrev',
  'app.promptWeightDown',
  'app.promptWeightUp',
]);

const formatHotkeyTitle = (id: string): string =>
  id
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .split(' ')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');

const hotkey = (category: HotkeyCategory, id: string, defaultKeys: string[]): HotkeyDefinition => {
  const commandId = `${category}.${id}`;

  return {
    allowInEditable: editableAppHotkeys.has(commandId),
    category,
    commandId,
    defaultKeys,
    id: commandId,
    implemented: implemented.has(commandId),
    preventDefault: true,
    scope: categoryScopes[category],
    title: formatHotkeyTitle(id),
  };
};

export const firstPartyHotkeyCatalog: HotkeyDefinition[] = [
  hotkey('app', 'invoke', ['mod+enter']),
  hotkey('app', 'invokeFront', ['mod+shift+enter']),
  hotkey('app', 'cancelQueueItem', ['shift+x']),
  hotkey('app', 'clearQueue', ['mod+shift+x']),
  hotkey('app', 'selectGenerateTab', ['1']),
  hotkey('app', 'selectCanvasTab', ['2']),
  hotkey('app', 'selectUpscalingTab', ['3']),
  hotkey('app', 'selectWorkflowsTab', ['4']),
  hotkey('app', 'selectModelsTab', ['5']),
  hotkey('app', 'selectQueueTab', ['6']),
  hotkey('app', 'promptHistoryPrev', ['alt+arrowup']),
  hotkey('app', 'promptHistoryNext', ['alt+arrowdown']),
  hotkey('app', 'promptWeightUp', ['ctrl+arrowup']),
  hotkey('app', 'promptWeightDown', ['ctrl+arrowdown']),
  hotkey('app', 'focusPrompt', ['alt+a']),
  hotkey('app', 'toggleLeftPanel', ['t', 'o']),
  hotkey('app', 'toggleRightPanel', ['g']),
  hotkey('app', 'resetPanelLayout', ['shift+r']),
  hotkey('app', 'togglePanels', ['f']),
  hotkey('canvas', 'selectBrushTool', ['b']),
  hotkey('canvas', 'selectBboxTool', ['c']),
  hotkey('canvas', 'decrementToolWidth', ['[']),
  hotkey('canvas', 'incrementToolWidth', [']']),
  hotkey('canvas', 'selectEraserTool', ['e']),
  hotkey('canvas', 'selectMoveTool', ['v']),
  hotkey('canvas', 'selectRectTool', ['u']),
  hotkey('canvas', 'selectLassoTool', ['l']),
  hotkey('canvas', 'selectViewTool', ['h']),
  hotkey('canvas', 'selectColorPickerTool', ['i']),
  hotkey('canvas', 'setFillColorsToDefault', ['d']),
  hotkey('canvas', 'toggleFillColor', ['x']),
  hotkey('canvas', 'fitLayersToCanvas', ['mod+0']),
  hotkey('canvas', 'fitBboxToCanvas', ['mod+shift+0']),
  hotkey('canvas', 'fitBboxToLayers', ['shift+n']),
  hotkey('canvas', 'setZoomTo100Percent', ['mod+1']),
  hotkey('canvas', 'setZoomTo200Percent', ['mod+2']),
  hotkey('canvas', 'setZoomTo400Percent', ['mod+3']),
  hotkey('canvas', 'setZoomTo800Percent', ['mod+4']),
  hotkey('canvas', 'quickSwitch', ['q']),
  hotkey('canvas', 'deleteSelected', ['delete', 'backspace']),
  hotkey('canvas', 'resetSelected', ['shift+c']),
  hotkey('canvas', 'mergeDown', ['mod+e']),
  hotkey('canvas', 'mergeVisible', ['mod+shift+e']),
  hotkey('canvas', 'transformSelected', ['shift+t']),
  hotkey('canvas', 'filterSelected', ['shift+f']),
  hotkey('canvas', 'invertMask', ['shift+v']),
  hotkey('canvas', 'undo', ['mod+z']),
  hotkey('canvas', 'redo', ['mod+shift+z', 'mod+y']),
  hotkey('canvas', 'nextEntity', ['alt+]']),
  hotkey('canvas', 'prevEntity', ['alt+[']),
  hotkey('canvas', 'applyFilter', ['enter']),
  hotkey('canvas', 'cancelFilter', ['esc']),
  hotkey('canvas', 'applyTransform', ['enter']),
  hotkey('canvas', 'cancelTransform', ['esc']),
  hotkey('canvas', 'applySegmentAnything', ['enter']),
  hotkey('canvas', 'cancelSegmentAnything', ['esc']),
  hotkey('canvas', 'toggleNonRasterLayers', ['shift+h']),
  hotkey('canvas', 'fitBboxToMasks', ['shift+b']),
  hotkey('canvas', 'toggleBbox', ['shift+o']),
  hotkey('workflows', 'addNode', ['shift+a', 'space']),
  hotkey('workflows', 'copySelection', ['mod+c']),
  hotkey('workflows', 'pasteSelection', ['mod+v']),
  hotkey('workflows', 'pasteSelectionWithEdges', ['mod+shift+v']),
  hotkey('workflows', 'selectAll', ['mod+a']),
  hotkey('workflows', 'deleteSelection', ['delete', 'backspace']),
  hotkey('workflows', 'undo', ['mod+z']),
  hotkey('workflows', 'redo', ['mod+shift+z', 'mod+y']),
  hotkey('viewer', 'toggleViewer', ['z']),
  hotkey('viewer', 'swapImages', ['c']),
  hotkey('viewer', 'nextComparisonMode', ['m']),
  hotkey('viewer', 'deleteImage', ['delete', 'backspace']),
  hotkey('viewer', 'loadWorkflow', ['w']),
  hotkey('viewer', 'recallAll', ['a']),
  hotkey('viewer', 'recallSeed', ['s']),
  hotkey('viewer', 'recallPrompts', ['p']),
  hotkey('viewer', 'remix', ['r']),
  hotkey('viewer', 'useSize', ['d']),
  hotkey('viewer', 'toggleMetadata', ['i']),
  hotkey('gallery', 'selectAllOnPage', ['mod+a']),
  hotkey('gallery', 'clearSelection', ['esc']),
  hotkey('gallery', 'galleryNavUp', ['up']),
  hotkey('gallery', 'galleryNavRight', ['right']),
  hotkey('gallery', 'galleryNavDown', ['down']),
  hotkey('gallery', 'galleryNavLeft', ['left']),
  hotkey('gallery', 'galleryNavUpAlt', ['alt+up']),
  hotkey('gallery', 'galleryNavRightAlt', ['alt+right']),
  hotkey('gallery', 'galleryNavDownAlt', ['alt+down']),
  hotkey('gallery', 'galleryNavLeftAlt', ['alt+left']),
  hotkey('gallery', 'deleteSelection', ['delete', 'backspace']),
  hotkey('gallery', 'remix', ['r']),
  hotkey('gallery', 'starImage', ['.']),
];
