# This is a state dict for the SD3.5 MMDiTX model.
# https://huggingface.co/stabilityai/stable-diffusion-3.5-large/blob/main/sd3.5_large.safetensors
sd3_sd_shapes = {
    "first_stage_model.decoder.conv_in.bias": [512],
    "first_stage_model.decoder.conv_in.weight": [512, 16, 3, 3],
    "first_stage_model.decoder.conv_out.bias": [3],
    "first_stage_model.decoder.conv_out.weight": [3, 128, 3, 3],
    "first_stage_model.decoder.mid.attn_1.k.bias": [512],
    "first_stage_model.decoder.mid.attn_1.k.weight": [512, 512, 1, 1],
    "first_stage_model.decoder.mid.attn_1.norm.bias": [512],
    "first_stage_model.decoder.mid.attn_1.norm.weight": [512],
    "first_stage_model.decoder.mid.attn_1.proj_out.bias": [512],
    "first_stage_model.decoder.mid.attn_1.proj_out.weight": [512, 512, 1, 1],
    "first_stage_model.decoder.mid.attn_1.q.bias": [512],
    "first_stage_model.decoder.mid.attn_1.q.weight": [512, 512, 1, 1],
    "first_stage_model.decoder.mid.attn_1.v.bias": [512],
    "first_stage_model.decoder.mid.attn_1.v.weight": [512, 512, 1, 1],
    "first_stage_model.decoder.mid.block_1.conv1.bias": [512],
    "first_stage_model.decoder.mid.block_1.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.mid.block_1.conv2.bias": [512],
    "first_stage_model.decoder.mid.block_1.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.mid.block_1.norm1.bias": [512],
    "first_stage_model.decoder.mid.block_1.norm1.weight": [512],
    "first_stage_model.decoder.mid.block_1.norm2.bias": [512],
    "first_stage_model.decoder.mid.block_1.norm2.weight": [512],
    "first_stage_model.decoder.mid.block_2.conv1.bias": [512],
    "first_stage_model.decoder.mid.block_2.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.mid.block_2.conv2.bias": [512],
    "first_stage_model.decoder.mid.block_2.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.mid.block_2.norm1.bias": [512],
    "first_stage_model.decoder.mid.block_2.norm1.weight": [512],
    "first_stage_model.decoder.mid.block_2.norm2.bias": [512],
    "first_stage_model.decoder.mid.block_2.norm2.weight": [512],
    "first_stage_model.decoder.norm_out.bias": [128],
    "first_stage_model.decoder.norm_out.weight": [128],
    "first_stage_model.decoder.up.0.block.0.conv1.bias": [128],
    "first_stage_model.decoder.up.0.block.0.conv1.weight": [128, 256, 3, 3],
    "first_stage_model.decoder.up.0.block.0.conv2.bias": [128],
    "first_stage_model.decoder.up.0.block.0.conv2.weight": [128, 128, 3, 3],
    "first_stage_model.decoder.up.0.block.0.nin_shortcut.bias": [128],
    "first_stage_model.decoder.up.0.block.0.nin_shortcut.weight": [128, 256, 1, 1],
    "first_stage_model.decoder.up.0.block.0.norm1.bias": [256],
    "first_stage_model.decoder.up.0.block.0.norm1.weight": [256],
    "first_stage_model.decoder.up.0.block.0.norm2.bias": [128],
    "first_stage_model.decoder.up.0.block.0.norm2.weight": [128],
    "first_stage_model.decoder.up.0.block.1.conv1.bias": [128],
    "first_stage_model.decoder.up.0.block.1.conv1.weight": [128, 128, 3, 3],
    "first_stage_model.decoder.up.0.block.1.conv2.bias": [128],
    "first_stage_model.decoder.up.0.block.1.conv2.weight": [128, 128, 3, 3],
    "first_stage_model.decoder.up.0.block.1.norm1.bias": [128],
    "first_stage_model.decoder.up.0.block.1.norm1.weight": [128],
    "first_stage_model.decoder.up.0.block.1.norm2.bias": [128],
    "first_stage_model.decoder.up.0.block.1.norm2.weight": [128],
    "first_stage_model.decoder.up.0.block.2.conv1.bias": [128],
    "first_stage_model.decoder.up.0.block.2.conv1.weight": [128, 128, 3, 3],
    "first_stage_model.decoder.up.0.block.2.conv2.bias": [128],
    "first_stage_model.decoder.up.0.block.2.conv2.weight": [128, 128, 3, 3],
    "first_stage_model.decoder.up.0.block.2.norm1.bias": [128],
    "first_stage_model.decoder.up.0.block.2.norm1.weight": [128],
    "first_stage_model.decoder.up.0.block.2.norm2.bias": [128],
    "first_stage_model.decoder.up.0.block.2.norm2.weight": [128],
    "first_stage_model.decoder.up.1.block.0.conv1.bias": [256],
    "first_stage_model.decoder.up.1.block.0.conv1.weight": [256, 512, 3, 3],
    "first_stage_model.decoder.up.1.block.0.conv2.bias": [256],
    "first_stage_model.decoder.up.1.block.0.conv2.weight": [256, 256, 3, 3],
    "first_stage_model.decoder.up.1.block.0.nin_shortcut.bias": [256],
    "first_stage_model.decoder.up.1.block.0.nin_shortcut.weight": [256, 512, 1, 1],
    "first_stage_model.decoder.up.1.block.0.norm1.bias": [512],
    "first_stage_model.decoder.up.1.block.0.norm1.weight": [512],
    "first_stage_model.decoder.up.1.block.0.norm2.bias": [256],
    "first_stage_model.decoder.up.1.block.0.norm2.weight": [256],
    "first_stage_model.decoder.up.1.block.1.conv1.bias": [256],
    "first_stage_model.decoder.up.1.block.1.conv1.weight": [256, 256, 3, 3],
    "first_stage_model.decoder.up.1.block.1.conv2.bias": [256],
    "first_stage_model.decoder.up.1.block.1.conv2.weight": [256, 256, 3, 3],
    "first_stage_model.decoder.up.1.block.1.norm1.bias": [256],
    "first_stage_model.decoder.up.1.block.1.norm1.weight": [256],
    "first_stage_model.decoder.up.1.block.1.norm2.bias": [256],
    "first_stage_model.decoder.up.1.block.1.norm2.weight": [256],
    "first_stage_model.decoder.up.1.block.2.conv1.bias": [256],
    "first_stage_model.decoder.up.1.block.2.conv1.weight": [256, 256, 3, 3],
    "first_stage_model.decoder.up.1.block.2.conv2.bias": [256],
    "first_stage_model.decoder.up.1.block.2.conv2.weight": [256, 256, 3, 3],
    "first_stage_model.decoder.up.1.block.2.norm1.bias": [256],
    "first_stage_model.decoder.up.1.block.2.norm1.weight": [256],
    "first_stage_model.decoder.up.1.block.2.norm2.bias": [256],
    "first_stage_model.decoder.up.1.block.2.norm2.weight": [256],
    "first_stage_model.decoder.up.1.upsample.conv.bias": [256],
    "first_stage_model.decoder.up.1.upsample.conv.weight": [256, 256, 3, 3],
    "first_stage_model.decoder.up.2.block.0.conv1.bias": [512],
    "first_stage_model.decoder.up.2.block.0.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.2.block.0.conv2.bias": [512],
    "first_stage_model.decoder.up.2.block.0.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.2.block.0.norm1.bias": [512],
    "first_stage_model.decoder.up.2.block.0.norm1.weight": [512],
    "first_stage_model.decoder.up.2.block.0.norm2.bias": [512],
    "first_stage_model.decoder.up.2.block.0.norm2.weight": [512],
    "first_stage_model.decoder.up.2.block.1.conv1.bias": [512],
    "first_stage_model.decoder.up.2.block.1.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.2.block.1.conv2.bias": [512],
    "first_stage_model.decoder.up.2.block.1.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.2.block.1.norm1.bias": [512],
    "first_stage_model.decoder.up.2.block.1.norm1.weight": [512],
    "first_stage_model.decoder.up.2.block.1.norm2.bias": [512],
    "first_stage_model.decoder.up.2.block.1.norm2.weight": [512],
    "first_stage_model.decoder.up.2.block.2.conv1.bias": [512],
    "first_stage_model.decoder.up.2.block.2.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.2.block.2.conv2.bias": [512],
    "first_stage_model.decoder.up.2.block.2.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.2.block.2.norm1.bias": [512],
    "first_stage_model.decoder.up.2.block.2.norm1.weight": [512],
    "first_stage_model.decoder.up.2.block.2.norm2.bias": [512],
    "first_stage_model.decoder.up.2.block.2.norm2.weight": [512],
    "first_stage_model.decoder.up.2.upsample.conv.bias": [512],
    "first_stage_model.decoder.up.2.upsample.conv.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.3.block.0.conv1.bias": [512],
    "first_stage_model.decoder.up.3.block.0.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.3.block.0.conv2.bias": [512],
    "first_stage_model.decoder.up.3.block.0.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.3.block.0.norm1.bias": [512],
    "first_stage_model.decoder.up.3.block.0.norm1.weight": [512],
    "first_stage_model.decoder.up.3.block.0.norm2.bias": [512],
    "first_stage_model.decoder.up.3.block.0.norm2.weight": [512],
    "first_stage_model.decoder.up.3.block.1.conv1.bias": [512],
    "first_stage_model.decoder.up.3.block.1.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.3.block.1.conv2.bias": [512],
    "first_stage_model.decoder.up.3.block.1.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.3.block.1.norm1.bias": [512],
    "first_stage_model.decoder.up.3.block.1.norm1.weight": [512],
    "first_stage_model.decoder.up.3.block.1.norm2.bias": [512],
    "first_stage_model.decoder.up.3.block.1.norm2.weight": [512],
    "first_stage_model.decoder.up.3.block.2.conv1.bias": [512],
    "first_stage_model.decoder.up.3.block.2.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.3.block.2.conv2.bias": [512],
    "first_stage_model.decoder.up.3.block.2.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.decoder.up.3.block.2.norm1.bias": [512],
    "first_stage_model.decoder.up.3.block.2.norm1.weight": [512],
    "first_stage_model.decoder.up.3.block.2.norm2.bias": [512],
    "first_stage_model.decoder.up.3.block.2.norm2.weight": [512],
    "first_stage_model.decoder.up.3.upsample.conv.bias": [512],
    "first_stage_model.decoder.up.3.upsample.conv.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.conv_in.bias": [128],
    "first_stage_model.encoder.conv_in.weight": [128, 3, 3, 3],
    "first_stage_model.encoder.conv_out.bias": [32],
    "first_stage_model.encoder.conv_out.weight": [32, 512, 3, 3],
    "first_stage_model.encoder.down.0.block.0.conv1.bias": [128],
    "first_stage_model.encoder.down.0.block.0.conv1.weight": [128, 128, 3, 3],
    "first_stage_model.encoder.down.0.block.0.conv2.bias": [128],
    "first_stage_model.encoder.down.0.block.0.conv2.weight": [128, 128, 3, 3],
    "first_stage_model.encoder.down.0.block.0.norm1.bias": [128],
    "first_stage_model.encoder.down.0.block.0.norm1.weight": [128],
    "first_stage_model.encoder.down.0.block.0.norm2.bias": [128],
    "first_stage_model.encoder.down.0.block.0.norm2.weight": [128],
    "first_stage_model.encoder.down.0.block.1.conv1.bias": [128],
    "first_stage_model.encoder.down.0.block.1.conv1.weight": [128, 128, 3, 3],
    "first_stage_model.encoder.down.0.block.1.conv2.bias": [128],
    "first_stage_model.encoder.down.0.block.1.conv2.weight": [128, 128, 3, 3],
    "first_stage_model.encoder.down.0.block.1.norm1.bias": [128],
    "first_stage_model.encoder.down.0.block.1.norm1.weight": [128],
    "first_stage_model.encoder.down.0.block.1.norm2.bias": [128],
    "first_stage_model.encoder.down.0.block.1.norm2.weight": [128],
    "first_stage_model.encoder.down.0.downsample.conv.bias": [128],
    "first_stage_model.encoder.down.0.downsample.conv.weight": [128, 128, 3, 3],
    "first_stage_model.encoder.down.1.block.0.conv1.bias": [256],
    "first_stage_model.encoder.down.1.block.0.conv1.weight": [256, 128, 3, 3],
    "first_stage_model.encoder.down.1.block.0.conv2.bias": [256],
    "first_stage_model.encoder.down.1.block.0.conv2.weight": [256, 256, 3, 3],
    "first_stage_model.encoder.down.1.block.0.nin_shortcut.bias": [256],
    "first_stage_model.encoder.down.1.block.0.nin_shortcut.weight": [256, 128, 1, 1],
    "first_stage_model.encoder.down.1.block.0.norm1.bias": [128],
    "first_stage_model.encoder.down.1.block.0.norm1.weight": [128],
    "first_stage_model.encoder.down.1.block.0.norm2.bias": [256],
    "first_stage_model.encoder.down.1.block.0.norm2.weight": [256],
    "first_stage_model.encoder.down.1.block.1.conv1.bias": [256],
    "first_stage_model.encoder.down.1.block.1.conv1.weight": [256, 256, 3, 3],
    "first_stage_model.encoder.down.1.block.1.conv2.bias": [256],
    "first_stage_model.encoder.down.1.block.1.conv2.weight": [256, 256, 3, 3],
    "first_stage_model.encoder.down.1.block.1.norm1.bias": [256],
    "first_stage_model.encoder.down.1.block.1.norm1.weight": [256],
    "first_stage_model.encoder.down.1.block.1.norm2.bias": [256],
    "first_stage_model.encoder.down.1.block.1.norm2.weight": [256],
    "first_stage_model.encoder.down.1.downsample.conv.bias": [256],
    "first_stage_model.encoder.down.1.downsample.conv.weight": [256, 256, 3, 3],
    "first_stage_model.encoder.down.2.block.0.conv1.bias": [512],
    "first_stage_model.encoder.down.2.block.0.conv1.weight": [512, 256, 3, 3],
    "first_stage_model.encoder.down.2.block.0.conv2.bias": [512],
    "first_stage_model.encoder.down.2.block.0.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.2.block.0.nin_shortcut.bias": [512],
    "first_stage_model.encoder.down.2.block.0.nin_shortcut.weight": [512, 256, 1, 1],
    "first_stage_model.encoder.down.2.block.0.norm1.bias": [256],
    "first_stage_model.encoder.down.2.block.0.norm1.weight": [256],
    "first_stage_model.encoder.down.2.block.0.norm2.bias": [512],
    "first_stage_model.encoder.down.2.block.0.norm2.weight": [512],
    "first_stage_model.encoder.down.2.block.1.conv1.bias": [512],
    "first_stage_model.encoder.down.2.block.1.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.2.block.1.conv2.bias": [512],
    "first_stage_model.encoder.down.2.block.1.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.2.block.1.norm1.bias": [512],
    "first_stage_model.encoder.down.2.block.1.norm1.weight": [512],
    "first_stage_model.encoder.down.2.block.1.norm2.bias": [512],
    "first_stage_model.encoder.down.2.block.1.norm2.weight": [512],
    "first_stage_model.encoder.down.2.downsample.conv.bias": [512],
    "first_stage_model.encoder.down.2.downsample.conv.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.3.block.0.conv1.bias": [512],
    "first_stage_model.encoder.down.3.block.0.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.3.block.0.conv2.bias": [512],
    "first_stage_model.encoder.down.3.block.0.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.3.block.0.norm1.bias": [512],
    "first_stage_model.encoder.down.3.block.0.norm1.weight": [512],
    "first_stage_model.encoder.down.3.block.0.norm2.bias": [512],
    "first_stage_model.encoder.down.3.block.0.norm2.weight": [512],
    "first_stage_model.encoder.down.3.block.1.conv1.bias": [512],
    "first_stage_model.encoder.down.3.block.1.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.3.block.1.conv2.bias": [512],
    "first_stage_model.encoder.down.3.block.1.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.down.3.block.1.norm1.bias": [512],
    "first_stage_model.encoder.down.3.block.1.norm1.weight": [512],
    "first_stage_model.encoder.down.3.block.1.norm2.bias": [512],
    "first_stage_model.encoder.down.3.block.1.norm2.weight": [512],
    "first_stage_model.encoder.mid.attn_1.k.bias": [512],
    "first_stage_model.encoder.mid.attn_1.k.weight": [512, 512, 1, 1],
    "first_stage_model.encoder.mid.attn_1.norm.bias": [512],
    "first_stage_model.encoder.mid.attn_1.norm.weight": [512],
    "first_stage_model.encoder.mid.attn_1.proj_out.bias": [512],
    "first_stage_model.encoder.mid.attn_1.proj_out.weight": [512, 512, 1, 1],
    "first_stage_model.encoder.mid.attn_1.q.bias": [512],
    "first_stage_model.encoder.mid.attn_1.q.weight": [512, 512, 1, 1],
    "first_stage_model.encoder.mid.attn_1.v.bias": [512],
    "first_stage_model.encoder.mid.attn_1.v.weight": [512, 512, 1, 1],
    "first_stage_model.encoder.mid.block_1.conv1.bias": [512],
    "first_stage_model.encoder.mid.block_1.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.mid.block_1.conv2.bias": [512],
    "first_stage_model.encoder.mid.block_1.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.mid.block_1.norm1.bias": [512],
    "first_stage_model.encoder.mid.block_1.norm1.weight": [512],
    "first_stage_model.encoder.mid.block_1.norm2.bias": [512],
    "first_stage_model.encoder.mid.block_1.norm2.weight": [512],
    "first_stage_model.encoder.mid.block_2.conv1.bias": [512],
    "first_stage_model.encoder.mid.block_2.conv1.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.mid.block_2.conv2.bias": [512],
    "first_stage_model.encoder.mid.block_2.conv2.weight": [512, 512, 3, 3],
    "first_stage_model.encoder.mid.block_2.norm1.bias": [512],
    "first_stage_model.encoder.mid.block_2.norm1.weight": [512],
    "first_stage_model.encoder.mid.block_2.norm2.bias": [512],
    "first_stage_model.encoder.mid.block_2.norm2.weight": [512],
    "first_stage_model.encoder.norm_out.bias": [512],
    "first_stage_model.encoder.norm_out.weight": [512],
    "model.diffusion_model.context_embedder.bias": [2432],
    "model.diffusion_model.context_embedder.weight": [2432, 4096],
    "model.diffusion_model.final_layer.adaLN_modulation.1.bias": [4864],
    "model.diffusion_model.final_layer.adaLN_modulation.1.weight": [4864, 2432],
    "model.diffusion_model.final_layer.linear.bias": [64],
    "model.diffusion_model.final_layer.linear.weight": [64, 2432],
    "model.diffusion_model.joint_blocks.0.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.0.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.0.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.0.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.0.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.0.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.0.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.0.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.0.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.0.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.0.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.0.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.0.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.0.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.0.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.0.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.0.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.0.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.0.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.0.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.0.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.0.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.0.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.0.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.1.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.1.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.1.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.1.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.1.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.1.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.1.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.1.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.1.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.1.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.1.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.1.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.1.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.1.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.1.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.1.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.1.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.1.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.1.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.1.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.1.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.1.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.1.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.1.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.10.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.10.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.10.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.10.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.10.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.10.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.10.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.10.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.10.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.10.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.10.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.10.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.10.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.10.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.10.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.10.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.10.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.10.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.10.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.10.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.10.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.10.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.10.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.10.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.11.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.11.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.11.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.11.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.11.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.11.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.11.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.11.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.11.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.11.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.11.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.11.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.11.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.11.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.11.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.11.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.11.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.11.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.11.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.11.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.11.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.11.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.11.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.11.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.12.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.12.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.12.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.12.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.12.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.12.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.12.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.12.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.12.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.12.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.12.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.12.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.12.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.12.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.12.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.12.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.12.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.12.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.12.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.12.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.12.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.12.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.12.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.12.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.13.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.13.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.13.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.13.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.13.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.13.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.13.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.13.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.13.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.13.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.13.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.13.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.13.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.13.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.13.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.13.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.13.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.13.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.13.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.13.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.13.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.13.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.13.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.13.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.14.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.14.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.14.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.14.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.14.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.14.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.14.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.14.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.14.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.14.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.14.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.14.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.14.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.14.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.14.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.14.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.14.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.14.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.14.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.14.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.14.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.14.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.14.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.14.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.15.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.15.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.15.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.15.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.15.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.15.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.15.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.15.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.15.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.15.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.15.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.15.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.15.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.15.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.15.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.15.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.15.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.15.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.15.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.15.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.15.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.15.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.15.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.15.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.16.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.16.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.16.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.16.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.16.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.16.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.16.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.16.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.16.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.16.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.16.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.16.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.16.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.16.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.16.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.16.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.16.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.16.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.16.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.16.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.16.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.16.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.16.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.16.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.17.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.17.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.17.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.17.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.17.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.17.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.17.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.17.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.17.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.17.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.17.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.17.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.17.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.17.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.17.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.17.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.17.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.17.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.17.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.17.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.17.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.17.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.17.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.17.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.18.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.18.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.18.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.18.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.18.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.18.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.18.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.18.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.18.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.18.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.18.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.18.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.18.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.18.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.18.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.18.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.18.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.18.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.18.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.18.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.18.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.18.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.18.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.18.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.19.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.19.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.19.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.19.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.19.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.19.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.19.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.19.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.19.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.19.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.19.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.19.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.19.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.19.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.19.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.19.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.19.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.19.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.19.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.19.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.19.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.19.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.19.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.19.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.2.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.2.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.2.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.2.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.2.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.2.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.2.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.2.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.2.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.2.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.2.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.2.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.2.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.2.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.2.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.2.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.2.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.2.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.2.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.2.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.2.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.2.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.2.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.2.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.20.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.20.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.20.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.20.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.20.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.20.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.20.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.20.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.20.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.20.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.20.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.20.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.20.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.20.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.20.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.20.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.20.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.20.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.20.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.20.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.20.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.20.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.20.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.20.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.21.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.21.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.21.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.21.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.21.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.21.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.21.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.21.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.21.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.21.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.21.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.21.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.21.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.21.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.21.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.21.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.21.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.21.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.21.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.21.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.21.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.21.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.21.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.21.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.22.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.22.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.22.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.22.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.22.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.22.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.22.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.22.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.22.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.22.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.22.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.22.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.22.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.22.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.22.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.22.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.22.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.22.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.22.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.22.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.22.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.22.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.22.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.22.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.23.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.23.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.23.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.23.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.23.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.23.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.23.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.23.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.23.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.23.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.23.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.23.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.23.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.23.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.23.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.23.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.23.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.23.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.23.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.23.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.23.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.23.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.23.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.23.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.24.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.24.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.24.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.24.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.24.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.24.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.24.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.24.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.24.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.24.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.24.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.24.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.24.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.24.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.24.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.24.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.24.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.24.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.24.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.24.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.24.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.24.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.24.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.24.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.25.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.25.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.25.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.25.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.25.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.25.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.25.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.25.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.25.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.25.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.25.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.25.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.25.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.25.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.25.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.25.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.25.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.25.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.25.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.25.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.25.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.25.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.25.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.25.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.26.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.26.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.26.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.26.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.26.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.26.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.26.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.26.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.26.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.26.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.26.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.26.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.26.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.26.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.26.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.26.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.26.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.26.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.26.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.26.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.26.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.26.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.26.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.26.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.27.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.27.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.27.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.27.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.27.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.27.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.27.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.27.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.27.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.27.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.27.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.27.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.27.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.27.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.27.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.27.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.27.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.27.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.27.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.27.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.27.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.27.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.27.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.27.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.28.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.28.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.28.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.28.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.28.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.28.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.28.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.28.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.28.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.28.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.28.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.28.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.28.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.28.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.28.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.28.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.28.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.28.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.28.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.28.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.28.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.28.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.28.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.28.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.29.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.29.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.29.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.29.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.29.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.29.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.29.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.29.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.29.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.29.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.29.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.29.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.29.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.29.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.29.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.29.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.29.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.29.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.29.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.29.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.29.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.29.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.29.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.29.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.3.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.3.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.3.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.3.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.3.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.3.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.3.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.3.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.3.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.3.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.3.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.3.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.3.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.3.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.3.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.3.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.3.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.3.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.3.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.3.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.3.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.3.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.3.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.3.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.30.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.30.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.30.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.30.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.30.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.30.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.30.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.30.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.30.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.30.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.30.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.30.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.30.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.30.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.30.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.30.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.30.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.30.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.30.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.30.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.30.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.30.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.30.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.30.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.31.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.31.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.31.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.31.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.31.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.31.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.31.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.31.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.31.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.31.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.31.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.31.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.31.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.31.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.31.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.31.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.31.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.31.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.31.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.31.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.31.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.31.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.31.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.31.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.32.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.32.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.32.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.32.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.32.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.32.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.32.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.32.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.32.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.32.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.32.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.32.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.32.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.32.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.32.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.32.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.32.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.32.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.32.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.32.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.32.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.32.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.32.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.32.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.33.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.33.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.33.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.33.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.33.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.33.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.33.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.33.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.33.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.33.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.33.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.33.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.33.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.33.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.33.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.33.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.33.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.33.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.33.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.33.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.33.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.33.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.33.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.33.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.34.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.34.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.34.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.34.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.34.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.34.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.34.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.34.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.34.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.34.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.34.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.34.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.34.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.34.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.34.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.34.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.34.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.34.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.34.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.34.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.34.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.34.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.34.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.34.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.35.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.35.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.35.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.35.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.35.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.35.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.35.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.35.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.35.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.35.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.35.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.35.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.35.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.35.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.35.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.35.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.35.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.35.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.35.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.35.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.35.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.35.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.35.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.35.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.36.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.36.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.36.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.36.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.36.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.36.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.36.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.36.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.36.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.36.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.36.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.36.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.36.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.36.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.36.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.36.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.36.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.36.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.36.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.36.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.36.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.36.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.36.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.36.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.37.context_block.adaLN_modulation.1.bias": [4864],
    "model.diffusion_model.joint_blocks.37.context_block.adaLN_modulation.1.weight": [4864, 2432],
    "model.diffusion_model.joint_blocks.37.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.37.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.37.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.37.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.37.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.37.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.37.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.37.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.37.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.37.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.37.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.37.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.37.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.37.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.37.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.37.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.4.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.4.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.4.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.4.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.4.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.4.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.4.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.4.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.4.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.4.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.4.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.4.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.4.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.4.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.4.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.4.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.4.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.4.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.4.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.4.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.4.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.4.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.4.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.4.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.5.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.5.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.5.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.5.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.5.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.5.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.5.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.5.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.5.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.5.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.5.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.5.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.5.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.5.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.5.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.5.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.5.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.5.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.5.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.5.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.5.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.5.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.5.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.5.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.6.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.6.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.6.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.6.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.6.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.6.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.6.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.6.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.6.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.6.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.6.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.6.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.6.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.6.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.6.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.6.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.6.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.6.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.6.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.6.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.6.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.6.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.6.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.6.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.7.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.7.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.7.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.7.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.7.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.7.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.7.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.7.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.7.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.7.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.7.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.7.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.7.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.7.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.7.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.7.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.7.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.7.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.7.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.7.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.7.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.7.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.7.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.7.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.8.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.8.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.8.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.8.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.8.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.8.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.8.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.8.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.8.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.8.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.8.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.8.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.8.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.8.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.8.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.8.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.8.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.8.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.8.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.8.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.8.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.8.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.8.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.8.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.9.context_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.9.context_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.9.context_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.9.context_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.9.context_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.9.context_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.9.context_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.9.context_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.9.context_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.9.context_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.9.context_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.9.context_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.joint_blocks.9.x_block.adaLN_modulation.1.bias": [14592],
    "model.diffusion_model.joint_blocks.9.x_block.adaLN_modulation.1.weight": [14592, 2432],
    "model.diffusion_model.joint_blocks.9.x_block.attn.ln_k.weight": [64],
    "model.diffusion_model.joint_blocks.9.x_block.attn.ln_q.weight": [64],
    "model.diffusion_model.joint_blocks.9.x_block.attn.proj.bias": [2432],
    "model.diffusion_model.joint_blocks.9.x_block.attn.proj.weight": [2432, 2432],
    "model.diffusion_model.joint_blocks.9.x_block.attn.qkv.bias": [7296],
    "model.diffusion_model.joint_blocks.9.x_block.attn.qkv.weight": [7296, 2432],
    "model.diffusion_model.joint_blocks.9.x_block.mlp.fc1.bias": [9728],
    "model.diffusion_model.joint_blocks.9.x_block.mlp.fc1.weight": [9728, 2432],
    "model.diffusion_model.joint_blocks.9.x_block.mlp.fc2.bias": [2432],
    "model.diffusion_model.joint_blocks.9.x_block.mlp.fc2.weight": [2432, 9728],
    "model.diffusion_model.pos_embed": [1, 36864, 2432],
    "model.diffusion_model.t_embedder.mlp.0.bias": [2432],
    "model.diffusion_model.t_embedder.mlp.0.weight": [2432, 256],
    "model.diffusion_model.t_embedder.mlp.2.bias": [2432],
    "model.diffusion_model.t_embedder.mlp.2.weight": [2432, 2432],
    "model.diffusion_model.x_embedder.proj.bias": [2432],
    "model.diffusion_model.x_embedder.proj.weight": [2432, 16, 2, 2],
    "model.diffusion_model.y_embedder.mlp.0.bias": [2432],
    "model.diffusion_model.y_embedder.mlp.0.weight": [2432, 2048],
    "model.diffusion_model.y_embedder.mlp.2.bias": [2432],
    "model.diffusion_model.y_embedder.mlp.2.weight": [2432, 2432],
}
