"""Canvas projects, and the documents of projects that lost their owner."""

from sqlalchemy import CheckConstraint, Column, ForeignKey, PrimaryKeyConstraint

from invokeai.app.services.shared.database.schema.metadata import (
    USER_ID_LENGTH,
    default,
    inserted_at,
    table,
    updated_at,
)
from invokeai.app.services.shared.database.types import BigInt, Key, LongText, Timestamp

projects = table(
    "projects",
    # Generated by the client; unique per user, not globally.
    Column("project_id", Key(), nullable=False),
    Column("user_id", Key(USER_ID_LENGTH), ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False),
    Column("name", LongText(), nullable=False),
    # The client's project document (JSON).
    Column("data", LongText(), nullable=False),
    # The project's own board. Unique: at most one project per board. RESTRICT: a claimed board cannot be deleted.
    Column("board_id", Key(), ForeignKey("boards.board_id", ondelete="RESTRICT"), nullable=False, unique=True),
    # Incremented on every update, for optimistic concurrency.
    Column("revision", BigInt(), nullable=False, server_default=default(1)),
    inserted_at(),
    updated_at(),
    Column("minimum_canvas_schema_version", BigInt(), nullable=False, server_default=default(2)),
    PrimaryKeyConstraint("user_id", "project_id"),
    CheckConstraint("minimum_canvas_schema_version >= 1", name="minimum_canvas_schema_version"),
)

# Where the project boards migration put projects whose owner no longer existed, whole, for repair. Free of
# foreign keys, so it can hold what `projects` cannot. Created by that migration only when it had such projects.
orphaned_projects_2026_08_06 = table(
    "orphaned_projects_2026_08_06",
    Column("project_id", Key(), nullable=False),
    Column("user_id", Key(USER_ID_LENGTH), nullable=False),
    Column("name", LongText(), nullable=False),
    Column("data", LongText(), nullable=False),
    Column("revision", BigInt(), nullable=False),
    Column("created_at", Timestamp(), nullable=False),
    Column("updated_at", Timestamp(), nullable=False),
    inserted_at("quarantined_at"),
    PrimaryKeyConstraint("user_id", "project_id"),
)
