/**
 * Video generation's React-free values/policy surface: settings normalization,
 * the per-base/per-variant capabilities matrix, canvas math, and model-selection
 * transitions. Curated, caller-driven export list — add a symbol only when a
 * consumer needs it. UI and graph compilation arrive in later modules.
 */
export type {
  MiniMaxH3TargetResolution,
  VideoAspectRatioId,
  VideoGenerationMode,
  VideoSettings,
  VideoSourceClip,
  VideoTargetResolution,
  VideoWidgetValues,
  WanTargetResolution,
} from './core/types';
export {
  clearDeletedVideoMedia,
  cloneVideoWidgetValues,
  createVideoSourceClip,
  isImageWithDims,
  isVideoAspectRatioId,
  isVideoSettings,
  isVideoSourceClip,
  isVideoTargetResolution,
  isVideoWidgetValues,
  MINIMAX_H3_TARGET_RESOLUTIONS,
  normalizeVideoSettings,
  normalizeVideoWidgetValues,
  resolveVideoMode,
  VIDEO_ASPECT_RATIO_IDS,
  VIDEO_UI_STATE_KEYS,
  WAN_TARGET_RESOLUTIONS,
} from './core/settings';
export {
  getVideoAspectRatioParts,
  getVideoDurationSeconds,
  invertVideoAspectRatioId,
  MINIMAX_H3_FPS,
  MINIMAX_H3_NUM_FRAMES_CHOICES,
  resolveMiniMaxH3Canvas,
  scaleAndSnapWanDimensions,
  WAN_NUM_FRAMES_DEFAULT,
  WAN_NUM_FRAMES_MAX,
  WAN_NUM_FRAMES_MIN,
  WAN_NUM_FRAMES_STEP,
  type VideoDimensions,
} from './core/dimensions';
export {
  findMiniMaxH3TurboLora,
  findWanLightningLoraPair,
  getAcceleratorToggleResult,
  getDefaultVideoSettings,
  getVideoComponentSectionPolicy,
  getVideoAspectRatioOptions,
  getVideoDimensions,
  getVideoModelAvailabilityReasons,
  getVideoModelPolicy,
  getVideoModelSelectionResult,
  getVideoTargetResolutionOptions,
  getWanExpertWiringWarning,
  getVideoModes,
  getVideoPromptPolicy,
  getVideoSettingsWithModelDefaults,
  getVideoValidationReasons,
  isSupportedVideoModel,
  isValidVideoNumFrames,
  isVideoModelSelectable,
  isVideoModeSupported,
  MINIMAX_H3_TURBO_ACCELERATOR,
  snapVideoNumFrames,
  SUPPORTED_VIDEO_BASES,
  VIDEO_GENERATION,
  WAN_LIGHTNING_ACCELERATOR,
  type ResolvedVideoDimensions,
  type VideoAcceleratorConfig,
  type SupportedVideoBase,
  type VideoComponentSectionPolicy,
  type VideoComponentSlotPolicy,
  type VideoComponentValueKey,
  type VideoFramesPolicy,
  type VideoModelPolicy,
  type VideoModelSelectionResult,
  type VideoTargetResolutionOption,
  type WanExpertWiringWarning,
} from './core/videoPolicies';
export { compileVideoGraph, type CompiledVideoGraph } from './core/graph';
export {
  createDefaultVideoWidgetValues,
  getVideoWidgetValidationReasons,
  resolveVideoSeed,
  syncVideoWidgetValuesWithModels,
} from './core/widgetValues';
export { VideoUiProvider, useVideoUi, useVideoUiActions, type VideoUiAdapter } from './ui/VideoUiContext';
