name: install frontend dependencies
description: Installs frontend dependencies with pnpm, with caching
runs:
  using: 'composite'
  steps:
    - name: setup node 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: setup cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-node22-python3.14-pnpm10-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node22-python3.14-pnpm10-store-
          ${{ runner.os }}-node22-python3.14-
          ${{ runner.os }}-

    - name: install frontend dependencies
      run: pnpm install --prefer-frozen-lockfile --ignore-scripts
      shell: bash
      working-directory: invokeai/frontend/web
