import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  ignore: [
    // This file is only used during debugging
    'src/app/store/middleware/debugLoggerMiddleware.ts',
    // Autogenerated types - shouldn't ever touch these
    'src/services/api/schema.ts',
    'src/features/nodes/types/v1/**',
    'src/features/nodes/types/v2/**',
  ],
  ignoreBinaries: ['only-allow'],
  paths: {
    'public/*': ['public/*'],
  },
};

export default config;
