import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  project: ['src/**/*.{ts,tsx}!'],
  ignore: [
    // This file is only used during debugging
    'src/app/store/middleware/debugLoggerMiddleware.ts',
    // Autogenerated types - shouldn't ever touch these
    'src/services/api/schema.ts',
    'src/features/nodes/types/v1/**',
    'src/features/nodes/types/v2/**',
    // TODO(psyche): maybe we can clean up these utils after canvas v2 release
    'src/features/controlLayers/konva/util.ts',
    // TODO(psyche): restore HRF functionality?
    'src/features/hrf/**',
  ],
  ignoreBinaries: ['only-allow'],
  paths: {
    'public/*': ['public/*'],
  },
};

export default config;
