import type { SettingsContribution } from '@platform/ui/settings/contracts';

export const gallerySettingsContribution: SettingsContribution = {
  id: 'gallery',
  label: (t) => t('widgets.labels.gallery'),
  fields: [
    {
      id: 'imageSize',
      kind: 'slider',
      label: (t) => t('widgets.gallery.imageSize'),
      group: (t) => t('widgets.gallery.settingsGridSize'),
      keywords: 'density thumbnails zoom',
      min: 0,
      max: 100,
      step: 1,
      scope: 'instance',
    },
    {
      id: 'thumbnailFit',
      kind: 'select',
      label: (t) => t('widgets.gallery.settingsThumbnails'),
      group: (t) => t('widgets.gallery.settingsThumbnails'),
      options: [
        { value: 'square', label: (t) => t('widgets.gallery.thumbnailFitSquare') },
        { value: 'aspect', label: (t) => t('widgets.gallery.thumbnailFitAspect') },
      ],
      scope: 'instance',
    },
    {
      id: 'showImageDimensions',
      kind: 'boolean',
      label: (t) => t('widgets.gallery.alwaysShowDimensions'),
      group: (t) => t('widgets.gallery.settingsThumbnails'),
      keywords: 'width height pixels',
      scope: 'instance',
    },
    {
      id: 'showPendingItems',
      kind: 'boolean',
      label: (t) => t('widgets.gallery.showPendingItems'),
      group: (t) => t('widgets.gallery.settingsThumbnails'),
      keywords: 'queue progress placeholders',
      scope: 'instance',
    },
    {
      id: 'paginationMode',
      kind: 'select',
      label: (t) => t('widgets.gallery.pagination'),
      group: (t) => t('widgets.gallery.pagination'),
      options: [
        { value: 'infinite', label: (t) => t('widgets.gallery.infinite') },
        { value: 'paginated', label: (t) => t('common.pages') },
      ],
      scope: 'instance',
    },
    {
      id: 'imageOrderDir',
      kind: 'select',
      label: (t) => t('widgets.gallery.imageSort'),
      group: (t) => t('widgets.gallery.pagination'),
      options: [
        { value: 'DESC', label: (t) => t('widgets.gallery.newest') },
        { value: 'ASC', label: (t) => t('widgets.gallery.oldest') },
      ],
      scope: 'instance',
    },
    {
      id: 'followSelectedBoard',
      kind: 'boolean',
      label: (t) => t('widgets.gallery.followSelectedBoard'),
      group: (t) => t('widgets.gallery.destination'),
      keywords: 'auto add board destination results workflow',
      scope: 'instance',
    },
    {
      id: 'showDateBoards',
      kind: 'boolean',
      label: (t) => t('widgets.gallery.dateBoards'),
      group: (t) => t('widgets.gallery.boardVisibility'),
      scope: 'instance',
    },
    {
      id: 'showArchivedBoards',
      kind: 'boolean',
      label: (t) => t('widgets.gallery.archivedBoards'),
      group: (t) => t('widgets.gallery.boardVisibility'),
      scope: 'instance',
    },
    {
      id: 'showOtherProjectBoards',
      kind: 'boolean',
      label: (t) => t('widgets.gallery.otherProjectBoards'),
      group: (t) => t('widgets.gallery.boardVisibility'),
      scope: 'instance',
    },
    {
      id: 'boardOrderBy',
      kind: 'select',
      label: (t) => t('widgets.gallery.sortBoardsBy'),
      group: (t) => t('widgets.gallery.filterAndSortBoards'),
      options: [
        { value: 'created_at', label: (t) => t('common.created') },
        { value: 'board_name', label: (t) => t('common.name') },
      ],
      scope: 'instance',
    },
    {
      id: 'boardOrderDir',
      kind: 'select',
      label: (t) => t('widgets.gallery.boardOrder', { defaultValue: 'Board order' }),
      group: (t) => t('widgets.gallery.filterAndSortBoards'),
      options: [
        { value: 'DESC', label: (t) => t('widgets.gallery.sortBoardsDescending') },
        { value: 'ASC', label: (t) => t('widgets.gallery.sortBoardsAscending') },
      ],
      scope: 'instance',
    },
  ],
  quick: ['imageSize', 'thumbnailFit', 'showImageDimensions', 'showPendingItems', 'paginationMode'],
  load: () => import('./ui/GallerySettingField').then((module) => ({ Field: module.GallerySettingField })),
};
